### ISSUE TITLE
`dlopen` issue with pytorch

### ISSUE THREAD

**Issue by christopherhesse** [VirtualGL/virtualgl#107]
Unclear if pytorch is doing something weird here, but:

```py
import torch
x=torch.zeros(3,device='cuda')
torch.cat([x,x])
```

This program works fine except when run under `vglrun` with `vglrun python -m oneoff.test_ld_library_issue`:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/code/sandbox/oneoff/test_ld_library_issue.py", line 3, in <module>
    torch.cat([x,x])
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
```

Running this program from `/opt/conda/lib/python3.7/site-packages/torch/lib` or setting `LD_LIBRARY_PATH=/opt/conda/lib/python3.7/site-packages/torch/lib` fixes the issue.

This seemed to happen with virtualgl 2.5.2 and 2.6.2.

Is this an issue with `libdlfaker.so`'s `dlopen` wrapper? Removing that library from `LD_PRELOAD` stops the error from happening.

**Comment by dcommander** [comment]
No idea.  VirtualGL's `dlopen()` wrapper does disable the `RTLD_DEEPBIND` flag, if the application passes it to `dlopen()`.  That's because, otherwise, an application could use `dlopen()` to open a library that subsequently calls OpenGL or GLX functions, and the nature of `RTLD_DEEPBIND` would mean that those functions would supercede VirtualGL's interposed versions of same, thus disabling VirtualGL.  Apart from that, however, the interposed `dlopen()` function in **libdlfaker.so** should not interfere unless it detects that the application is trying to use `dlopen()` to open the OpenGL or X11 shared library.

I can certainly add the workaround to VirtualGL's list of application recipes.  Does this affect only pytorch, or does it affect other Python modules?

**Comment by christopherhesse** [comment]
Hmm, does `dlopen()` have some behavior where it will look up paths relative to the `.so` performing the `dlopen()` call?  I don't see how `RTLD_DEEPBIND` would cause a failure to find the `.so`.

**Comment by christopherhesse** [comment]
`LD_PRELOAD=libdlfaker.so:libvglfaker.so strace python -m oneoff.test_ld_library_issue 2> vgl.txt`

`strace python -m oneoff.test_ld_library_issue 2> normal.txt`

```grep libcaffe2_nvrtc *.txt                                                                                                                                                
normal.txt:open("/root/.mujoco/mujoco200/bin/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("/root/.mujoco/mjpro150/bin/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("tls/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("tls/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
normal.txt:open("/opt/conda/lib/python3.7/site-packages/torch/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = 24
vgl.txt:open("/opt/conda/bin/../lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/root/.mujoco/mujoco200/bin/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/root/.mujoco/mjpro150/bin/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("tls/x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("tls/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("x86_64/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/lib/x86_64-linux-gnu/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/usr/lib/x86_64-linux-gnu/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:open("/usr/lib/libcaffe2_nvrtc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
vgl.txt:write(2, "Error in dlopen or dlsym: libcaf"..., 103Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory) = 103
```

Is there something obvious I am missing?  Without the `LD_PRELOAD` it searches the correct path and then with it, it does not.

**Comment by dcommander** [comment]
I'm wondering if **libcaffe2_nvrtc.so** was linked with an RPATH of `$ORIGIN`.  If so, then yes, that would cause any path references relative to `$ORIGIN` to resolve to paths that are relative to the location of **libdlfaker.so** rather than the location of **libcaffe2_nvrtc.so**.  A similar known issue exists with the Intel OpenCL installable client driver: https://cdn.rawgit.com/VirtualGL/virtualgl/2.6.2/doc/index.html#hd0015.

`-nodl` is a valid workaround as long as the application (or the frameworks it uses) won't ever need to use `dlopen()` to open the OpenGL or X11 libraries.  Otherwise, passing `-ld {path-to-libcaffe2_nvrtc.so}` to `vglrun` is the suggested workaround.

**Comment by christopherhesse** [comment]
Yeah I think you're correct, thanks for the help!  It would be nice if a workaround was not required, but at least it is straightforward.

**Comment by dcommander** [comment]
Sure it would be nice if a workaround was not required, but I have no idea how to accomplish that.  If you have any ideas, I'm happy to look into them.

**Comment by christopherhesse** [comment]
Nah, thanks for the help!

**Comment by dcommander** [comment]
Confirmed that all of the PyTorch DSOs have an RPATH of `$ORIGIN`.  I will document the workaround as an app recipe.
