### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [VirtualGL/virtualgl#110]
I would like to point out that identifiers like “[`__SOCKET_H__`](https://github.com/VirtualGL/virtualgl/blob/723f88ab40e982b779661211ae9dcabff4bcc659/include/Socket.h#L15 "Update candidate")” and “[`__VGLUTIL_H__`](https://github.com/VirtualGL/virtualgl/blob/86343debafd3daf2fec025870f6b4bafc1ab86c6/include/vglutil.h#L16 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dcommander** [comment]
If those were external API headers, then I would be concerned about C++ naming conventions, but VirtualGL itself doesn't use the STL, so I think the chances of a name collision are approximately zero.  VirtualGL has used that convention for guaranteeing exclusivity of internal headers for 15 years, and there hasn't ever been a problem.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by dcommander** [comment]
How does it depend on undefined behavior? If there are specific issues with the code— particularly if those issues can be detected with UBSan— then point out those issues.

**Comment by elfring** [comment]
I suggest to [reduce the tampering with the reserved name space](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by dcommander** [comment]
Point out specific examples, please. You’re not making sense.

**Comment by elfring** [comment]
Double underscores are used in include guards (for example) from this software in inappropriate ways.
:crystal_ball: Would you like to achieve C++ standard compliance?

**Comment by dcommander** [comment]
I’ve already answered that question. They are internal headers, and there are no known issues that arise from their use of double underscores.

**Comment by elfring** [comment]
>They are internal headers,

This categorisation does not matter for remaining software development concerns.


>and there are no known issues that arise from their use of double underscores.

I am just trying again to [increase the awareness on another open issue](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for reserved identifiers").

**Comment by dcommander** [comment]
> This categorisation does not matter for remaining software development concerns.

I disagree. The headers in question are only included by other code within VirtualGL. If there were a conflict, then the build would fail. Obviously it doesn’t. Furthermore, many C headers use underscores in macro identifiers, and such headers are included by C++ code. The underscores are meant to *avoid* name conflicts, so I don’t understand why the C++ spec cares about them. I also don’t understand why you are so narrowly focused on such a nit-picky issue in such a low-traffic project as this. Furthermore, VirtualGL is a hybrid C/C++ project, so of course not every part of it can conform to the C++ spec— particularly if you’re talking about C++11, which post-dates VGL. I would consider making these changes in the context of a supportable workflow, such as if I could use a particular compiler option to test for such conformance issues. Otherwise, it is likely that other non-user-visible conformance issues would creep back into the code over time, and I do not have the resources to constantly review the code for such issues.

**Comment by elfring** [comment]
>The underscores are meant to avoid name conflicts,

The intention is clear (in principle).


>so I don’t understand why the C++ spec cares about them.

This view can be a problem if you pay insufficient development attention for information around undefined software behaviour.
How do you think about to improve static source code analysis?

**Comment by dcommander** [comment]
I’m sorry, but your answer does not make sense. Why does using underscores in a preprocessor macro produce “undefined” behavior? The same preprocessor is used for both C and C++ code.

**Comment by elfring** [comment]
>Why does using underscores in a preprocessor macro produce “undefined” behavior?

I suggest to take another look at the standard documents where the information is provided at various places that a software behaviour is unspecified or undefined.
Tampering with reserved identifiers can trigger corresponding software development concerns.

**Comment by dcommander** [comment]
Parroting a talking point is not the same as explaining it.  I am more concerned with the "spirit of the law" than the "letter of the law."  I have read the document you linked above.  It says, "Such a name may clash with reserved names defined by the implementation of the C++ standard template library in its headers or with reserved names implicitly predefined by the compiler even when no C++ standard library header is included."  Since we don't use the STL, that is a non-issue, and since our usage of the C++ standard library is very limited, that is a non-issue as well.  I only fix actual issues, not hypothetical ones.  This matter is closed.
