### ISSUE TITLE
How glXSwapBuffers() intercepted all 3D games successfully in virtualGL?

### ISSUE THREAD

**Issue by liuty10** [VirtualGL/virtualgl#118]
I have also tried to write a simple lib to intercept glXSwapBuffers() in 3D games. I can only intercept SuperTuxKart successfully, and the 0ad and dota2 don't work with this small lib. Do you have any ideas about that? How glXSwapBuffers() intercepted all 3D games successfully in virtualGL? I have also tried to use "extern "C" for definition and declearation, but it still doesn't work for other 3D games.

Here is my code:

`
// How to compile:
//      gcc -shared -fPIC -o libinterceptglx.so interceptglx.c
// How to use:
//      LD_PRELOAD=${PATH_TO_THIS_LIB}/libinterceptglx.so ./game_scripts.sh
#define _GNU_SOURCE
#include <X11/Xlib.h>
#include <GL/glx.h>
#include <stdio.h>
#include <stdint.h>
#include <dlfcn.h>
#include <time.h>
long long gettime_nanoTime(void)
{
    struct timespec __tv;
    clock_gettime(CLOCK_MONOTONIC,&__tv);
    return(long long)(__tv.tv_sec * 1e9 + __tv.tv_nsec);
}

void glXSwapBuffers(Display *dpy, GLXDrawable drawable){
    static void(*real_swapbuffer)(Display *, GLXDrawable) = NULL;
    static long long last_time_tmp0=0;
    static long long time_tmp0=0;
    static long long time_tmp1=0;
    if(!real_swapbuffer)
        real_swapbuffer = dlsym(RTLD_NEXT, "glXSwapBuffers");

    time_tmp0 = gettime_nanoTime();

    if(time_tmp1!=0){
        fprintf(stderr, "App time: %f, oneFrameTime: %f\n",
                           (time_tmp0-time_tmp1)/1000000.0,
                           (time_tmp0-last_time_tmp0)/1000000.0);
    }
    last_time_tmp0 = time_tmp0;
    real_swapbuffer(dpy, drawable);
    time_tmp1 = gettime_nanoTime();
}

**Comment by dcommander** [comment]
What exactly are you trying to do?  It is very unclear.  Why do you say "also" without providing any prior context?

**Comment by liuty10** [comment]
Sorry for the confusion. 
I am trying to get the time interval between glxswapbuffers of each pure 3d games(run on local computers without using TurboVNC or VirtualGL). When I use the simple code above, I can only intercept one game successfully. Since I have noticed that VirtualGL can successfully intercept all the 3D games. I wonder how VirtualGL do the interception successfully. 
"Also" means I am trying to write this simple lib in they way VirtualGL do. But, I am not sure how VirtualGL does interception for glXSwapBuffers().
Thank you very much!

**Comment by dcommander** [comment]
Yes, VirtualGL does intercept `glXSwapBuffers()`, and you could easily accomplish what you want by simply adding that new timing code to VirtualGL's existing `glXSwapBuffers()` implementation (refer to **server/faker-glx.cpp**.)  If you want to use your own interposer rather than modifying VirtualGL, then here is the basic strategy:

1. Develop your interposer as as standalone interposer library.  You can borrow some of the VirtualGL symbol loader code to achieve this, if you want (just bear in mind that VirtualGL is LGPL-licensed.)
2. Verify that your new interposer works properly without VirtualGL, by using `LD_PRELOAD` to load the interposer into various OpenGL applications.
3. Use the `VGL_GLLIB` environment variable to instruct VirtualGL to load GLX symbols from your interposer.  That means that VGL will pick up your version of `glXSwapBuffers()` ahead of the `glXSwapBuffers()` symbol in libGL.

**Comment by liuty10** [comment]
what do you mean by the "some of the VirtualGL symbol loader code"? Do you mean the code below?
`if(!real_swapbuffer)
real_swapbuffer = dlsym(RTLD_NEXT, "glXSwapBuffers");`

Do you have any idea why the code(the simple library I wrote) above doesn't work for all 3D applications in Linux?

**Comment by dcommander** [comment]
> what do you mean by the "some of the VirtualGL symbol loader code"? Do you mean the code below?

I mean the code in **server/faker-sym.cpp** and **server/faker-sym.h**.

> Do you have any idea why the code(the simple library I wrote) above doesn't work for all 3D applications in Linux?

Probably because some of those applications are using `dlopen()` to load GLX symbols rather than directly linking with libGL.  VirtualGL handles that scenario via its `dlopen()` interposer.  Your code does not.  However, if you follow my suggestions above, your code doesn't have to handle that scenario.  You can simply use VirtualGL on the front end and your interposer on the back end, so VGL will have already taken care of `dlopen()` for you.  Or, as I said, you can simply modify the VirtualGL code rather than trying to re-invent the wheel.
