### ISSUE TITLE
vglrun starts off fine after a graphics manager reset but slows to a crawl after several minutes

### ISSUE THREAD

**Issue by csideris** [VirtualGL/virtualgl#120]
If I execute "init 3" followed by "init 5" and then run the CUDA 10.2 sample marchingCubes, everything runs smoothly:

[csideris@acmehpc marchingCubes]$ vglrun +pr ./marchingCubes
[./marchingCubes] - Starting...
MarchingCubes
GPU Device 0: "Volta" with compute capability 7.0

grid: 32 x 32 x 32 = 32768 voxels
max verts = 102400
Read './data/Bucky.raw', 32768 bytes
Readback    -  391.34 Mpixels/sec- 1492.85 fps
Blit        -  600.59 Mpixels/sec- 2291.08 fps
Total       -   26.03 Mpixels/sec-   99.31 fps

If I close the program and just wait for some time to pass and then run it again, everything has slowed down to a crawl. Even though Readback and Blit are still just as fast, Total for some reason is now only 1fps:

[csideris@acmehpc marchingCubes]$ vglrun +pr ./marchingCubes
[./marchingCubes] - Starting...
MarchingCubes
GPU Device 0: "Volta" with compute capability 7.0

grid: 32 x 32 x 32 = 32768 voxels
max verts = 102400
Read './data/Bucky.raw', 32768 bytes
Readback    -  174.33 Mpixels/sec-  665.00 fps
Blit        -  379.08 Mpixels/sec- 1446.06 fps
Total       -    0.39 Mpixels/sec-    1.50 fps
Readback    -  385.25 Mpixels/sec- 1469.62 fps
Blit        -  446.96 Mpixels/sec- 1705.00 fps
Total       -    0.26 Mpixels/sec-    1.00 fps
 
I am using RealVNC VNC viewer to connect to my server, which is a Linux server running CentOS 7. Here are the graphics card specs:

[csideris@acmehpc marchingCubes]$ nvidia-smi
Wed Apr 15 15:58:54 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             Off  | 00000000:18:00.0  On |                  N/A |
| 28%   37C    P2    35W / 250W |    383MiB / 12066MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    184841      G   /usr/bin/X                                    50MiB |
|    0    185278    C+G   ./marchingCubes                              318MiB |
+-----------------------------------------------------------------------------+

Perhaps I should open another issue for this, but AnsysEM HFSS has also stopped working properly with vglrun. The software launches, but when it goes to render anything it completely freezes and the process must be killed...

Any help would be much appreciated! Thanks!

**Comment by dcommander** [comment]
The performance problem is a known issue with nVidia 440 and later.  Try adding
```
Option         "HardDPMS" "false"
```
in both the "Device" and "Screen" sections of your xorg.conf file.

And yes, please open a separate issue for ANSYS.

**Comment by csideris** [comment]
I added those entries and it seems to work fine now. Thanks! Ansys still crashes-- I opened a new issue for this.

**Comment by dcommander** [comment]
I have reproduced this issue on my Quadro K5000 under CentOS 7.7.  Some additional notes:

* If the issue exists, then it can immediately be reproduced by running:

   ```
   xauth merge /etc/opt/VirtualGL/vgl_xauth_key
   xset -display :0 dpms force off
   ```
   (Replace `:0` with the X display of your 3D X server, if necessary, and remove the `xauth` command if you aren't using the vglusers group to limit 3D X server access.)

   Otherwise, the issue will occur whenever DPMS is triggered on the display, which is usually after 10 minutes.

* In addition to disabling the `HardDPMS` option in **xorg.conf**, you can also temporarily disable DPMS to eliminate the issue:

   ```
   xset -display :0 -dpms
   ```

Refer to https://forums.developer.nvidia.com/t/440-36-with-bumblebee-drops-to-1-fps-after-running-for-10-minutes/108431.  It has been proposed that nVidia disable `HardDPMS` by default if the X server is configured for headless operation, which I believe would be a good idea.  Unfortunately, there isn't much that VirtualGL can do to work around this, since it's a driver feature that doesn't exist on other GPUs.  I have, however, updated the [Headless nVidia Mini How-To](https://virtualgl.org/Documentation/HeadlessNV) to reflect the current need to add `HardDPMS` to **xorg.conf** when configuring headless operation with 440.xx and later.

**Comment by karlkleinpaste** [comment]
I just wanted to say thank you for the mention of this report in other recent reports. I had been vexed by this problem for the last 2 months on 1 particular machine, could not understand why only it had problems with 1fps operation. For now, I've arranged to do "DISPLAY=:0 xset -dpms" when starting up in Xvnc. Very useful.

**Comment by Dyotty** [comment]
I posted the above issue
https://github.com/TurboVNC/turbovnc/issues/249
I don't know if it's the same as my problem, but I noticed that it occurs when the screen of display :0 is locked.
Unfortunately https://github.com/VirtualGL/virtualgl/issues/120#issuecomment-624904532 didn't work for me.
It was solved by setting display :0 not to lock.

**Comment by dcommander** [comment]
You mean disabling `HardDPMS` in xorg.conf didn’t work? It has worked for everyone else who has reported this problem.
