### ISSUE TITLE
vglserver_config: uninstall incomplete

### ISSUE THREAD

**Issue by fnatter** [VirtualGL/virtualgl#122]
dear developers,

many thanks this extremely useful program!

There is one small thing: If you:
- run vglserver_config with n/n/n (do not restrict to vglusers group)
- reboot
- test...
- uninstall using vglserver_config
- run vglserver_config with y/y/n (*do* restrict to vglusers group)
- reboot

Then 'vglrun' still runs for my user which is not in the vglusers group.
I think this is an important use case: You first test with no restriction, then
you enable vgl securely.

Many Thanks!
Felix

**Comment by fnatter** [comment]
This is on Debian10. I tried to do it myself, but the script is quite long/complex...

**Comment by dcommander** [comment]
I can't reproduce, but perhaps an explanation of how the permissions system is supposed to work will help you diagnose the issue.

When you use `vglserver_config` to configure 3D X server access for all users, that causes `xhost +LOCAL:` to be run as a greeter autostart script in the display manager.  When you use `vglserver_config` to configure 3D X server access for only the `vglusers` group, that causes `vglgenkey` to be run as a greeter autostart script in the display manager.  `vglgenkey` copies the existing display manager Xauth cookie to **/etc/opt/VirtualGL/vgl_xauth_key**.  `vglrun` attempts to execute `xauth merge /etc/opt/VirtualGL/vgl_xauth_key`, which merges the display manager/3D X server Xauth cookie with the user's **~/.Xauthority** file.  That will only succeed if the user is a member of `vglusers`, because **/etc/opt/VirtualGL/vgl_xauth_key** can only be read by the `vglusers` group.

On Debian 10, the display manager Xauth cookie only changes when the system is rebooted.  Thus, if a user already had that cookie in their **~/.Xauthority** file, that user would still be able to access the 3D X server even if they had just been removed from `vglusers`.  That doesn't exactly fit your reported symptoms, since you rebooted before observing the issue, but again, I'm explaining how it's supposed to work in hope that you can diagnose where it went wrong.

**Comment by dcommander** [comment]
Closing due to lack of response.  If you have any further information that may help me reproduce the issue, please add a comment.
