### ISSUE TITLE
Crash on new nvidia vgpu driver

### ISSUE THREAD

**Issue by wiad** [VirtualGL/virtualgl#123]
After updating to latest nvidia drivers in our VMware vGPU environment (440.56, https://docs.nvidia.com/grid/latest/grid-vgpu-release-notes-vmware-vsphere/index.html) applications launched with vglrun crashes during certain operations, for example resizing windows or zooming. When the application crashes the process loses its connection to the GPU (not longer listed in 'nvidia-smi') and starts consuming 100%cpu. 

At first we thought it was the nvidia driver of course, but we have tested direct access to GPU with x11vnc and haven't been able to reproduce the crash there. However we cannot reproduce the crash with the same virtualgl version on an older nvidia driver, so it seems to be a combination of 
virtualgl and the new nvidia driver. 

We can easily reproduce this by:
1. connect to server with vncviewer
2. start xfce session
3. Run 'vglrun glxgears'
4. Repeatedly resize the glxgears window
5. glxgears window turns black within 30-60s of resizing - crash. 

Here is a trace from vglrun:
```
[VGL 0xd540ab80] glViewport (x=0 y=0 width=911 height=383 ) 0.007153 ms
[VGL 0xd540ab80] handleEvent (xe->xconfigure.width=972 xe->xconfigure.height=389 xe->xconfigure.window=0x01e00002 ) 0.000000 ms
[VGL 0xd540ab80] glViewport (x=0 y=0 width=972 height=389 draw=0x006000d1 newDraw=0x006000d2 read=0x006000d1 newRead=0x006000d2 ) 7.092953 ms
[VGL 0xd540ab80] glXSwapBuffers (dpy=0x56016ea1cd50(:3.0) drawable=0x01e00002 vw->getGLXDrawable()=0x006000d2 ) 4.528046 ms
[VGL 0xd540ab80] handleEvent (xe->xconfigure.width=972 xe->xconfigure.height=389 xe->xconfigure.window=0x01e00002 ) 0.000000 ms
[VGL 0xd540ab80] glViewport (x=0 y=0 width=972 height=389 ) 0.005960 ms
[VGL 0xd540ab80] glXSwapBuffers (dpy=0x56016ea1cd50(:3.0) drawable=0x01e00002 vw->getGLXDrawable()=0x006000d2 ) 16.411066 ms
[VGL 0xd540ab80] handleEvent (xe->xconfigure.width=993 xe->xconfigure.height=394 xe->xconfigure.window=0x01e00002 ) 0.000000 ms
[VGL 0xd540ab80] glViewport (x=0 y=0 width=993 height=394 draw=0x006000d2 newDraw=0x006000d3 read=0x006000d2 newRead=0x006000d3 ) 8.841038 ms
[VGL 0xd540ab80] glXSwapBuffers (dpy=0x56016ea1cd50(:3.0) drawable=0x01e00002  <---- CRASH
```

Any ideas what could cause this issue?

**Comment by wiad** [comment]
This happens on both RHEL7 and RHEL8 servers with VirtualGL 2.6.3 and 2.6.2, in combination with the new nvidia driver.

**Comment by dcommander** [comment]
You've established that the crash only occurs with the newer nVidia driver and VirtualGL, but have you established that it only occurs with VMWare?  That is another critical datapoint.

I doubt that I'll be able to reproduce the issue, given that my only nVidia GPUs are in the Quadro family (and only one of those is still supported in the latest driver release.)  In my experience, when an issue occurs only with VirtualGL but goes away after you change the driver version, it's due to a driver bug that is exposed because VirtualGL activates GLX/OpenGL functionality behind the scenes (specifically, Pbuffer rendering and PBO readback) that wouldn't normally be activated by an OpenGL application running on the local display.  Historically, I've been able to work around a few of those bugs in the nVidia drivers, but the workarounds are never pretty, and in a few cases, the workarounds broke other things once the driver bug was actually fixed.

If we can isolate specifically what functionality is causing the crash and craft a simple test program to reproduce it outside of VirtualGL, then nVidia would likely fix it, but I couldn't personally help you in that regard unless I had the ability to reproduce the crash.

**Comment by dcommander** [comment]
Some things you might try:

Set `VGL_READBACK=sync` and see if the problem goes away (that would mean that the problem is with nVidia's implementation of PBOs, and if so, it may also be reproducible by running `/opt/VirtualGL/bin/glreadtest -pbo` on the local display.)

Set `VGL_DRAWABLE=pixmap` and see if the problem goes away (that would mean that the problem is with nVidia's implementation of Pbuffers, and it may also be reproducible with `/opt/VirtualGL/bin/glreadtest` or one of the Pbuffer demos under **glxdemos/**.)

Set `VGL_FORCEALPHA=1` and `VGL_DEFAULTFBCONFIG=GLX_ALPHA_SIZE,8` and see if the problem goes away.

**Comment by wiad** [comment]
Thanks for the debugging tips, I really appreciate it. Unfortunately I could not get rid of the problem with any of them. 

However, we discovered that there were another branch of drivers for VMware vgpu which were the long-term-support branch rather than the 'new features'-branch we've been using. We tested that driver which seems to have resolved the issue. We have reported it to nvidia (who recommended us to use the longterm driver), so hopefully they'll fix it. 

Thanks! (closing)
