### ISSUE TITLE
Windows installers not available on sourceforge download pages

### ISSUE THREAD

**Issue by markstock** [VirtualGL/virtualgl#125]
This maybe a naive question, but I'm looking for the installers for VirtualGL for Windows on https://sourceforge.net/projects/virtualgl/files/2.6.3/ and all I see are the Utils exes for x86 and x64. Are the full installers not being generated any more? The installation instructions on https://virtualgl.org/vgldoc/2_2_1/#hd004004 seem to imply that the installers are there.

**Comment by dcommander** [comment]
Why would you expect the installation instructions for VirtualGL 2.2.1, which was released nearly 10 years ago, to apply to 2.6.3, which was released this year?  The installation instructions for VGL 2.2.1 apply to VGL 2.2.1 and only to VGL 2.2.1.  I refer you to 

https://github.com/VirtualGL/virtualgl/blob/master/ChangeLog.md#2390-24-beta1

which explains that VirtualGL 2.3.3 was the last release to provide the VirtualGL Client for Exceed.  That client still probably works with more recent VirtualGL servers, since nothing has changed in the VGL Transport protocol since then.  However, it isn't officially supported anymore.  If you want an officially supported solution, use Cygwin/X or TurboVNC.  TurboVNC is recommended for new users, since it has minimal client-side requirements.

**Comment by markstock** [comment]
I'm sorry - that was the top hit for documentation for virtualGL, I've used it in the past, and much of the information there is still relevant (for Linux, at least). I only looked through the first half-dozen release notes here to find information about a missing Windows installer, to no avail. We are trying TurboVNC now.

**Comment by dcommander** [comment]
I cannot control which results Google returns.  I can only control what is on my own site:
https://virtualgl.org/Documentation/Documentation
(incidentally, that is the first link returned when you google "virtualgl documentation" as opposed to "virtualgl user's guide".)

In general, best practices dictate that you should go directly to the project web site when looking for the latest information about an open source project.
