### ISSUE TITLE
Performance loose?

### ISSUE THREAD

**Issue by Askmewho** [VirtualGL/virtualgl#127]
Hi! I've tested this on rpi4 and I noted a massive drop in Performance on glmark while it's clearly hw accelerated (I mean, checked).this is normal behavior??

**Comment by dcommander** [comment]
GLmark is a very fine-grained benchmark, so the small amount of per-frame overhead that VirtualGL produces will have a noticeable impact on its performance. GLmark is not meant to measure realistic application performance. It’s meant to measure raw GPU performance without human interaction. VirtualGL’s entire purpose is enabling humans to remotely interact with 3D applications, so benchmarks designed to measure performance without human interaction don’t have much meaning with VGL. Similarly, GLXgears doesn’t have much meaning with VGL, because its geometry is so small that modern GPUs can render it at thousands of frames per second, but the human eye can only process about 60 frames per second. Back in the days when GPUs could only render hundreds of thousands of polys per second (before the term “GPU” even existed, incidentally), we used to talk of GPU performance as “geometry-limited” (that is, limited by the throughout of the front end of the 3D rendering pipeline) or “fill-rate-limited” (that is, limited by the throughout of the back end of the pipeline.) In terms of performance, VGL acts sort of like an extreme case of a fill-rate-limited GPU, which means that it introduces overhead for each frame but not for each primitive. I don’t know exactly how GLmark works, but if it doesn’t matter whether the pixels it renders actually end up on the screen, then you may be able to reduce or eliminate most of VGL’s per-frame overhead by setting `VGL_READBACK=none` in the environment.
