### ISSUE TITLE
OpenGL versions differs  in TurboVNC Server and Client in the same machine.

### ISSUE THREAD

**Issue by zenny** [VirtualGL/virtualgl#13]
Hi,

This is a bit strange for me,

TurboVNC Server (localhost):

```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD CAICOS
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

TurboVNC Client on same machine:

```
$ glxinfo | grep OpenGL
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: r600
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL extensions:

```

And when I tried with the TurboVNCviewer Window itself, I got:

```
$ glxinfo | grep OpenGL
Error: couldn't find RGB GLX visual or fbconfig
Error: couldn't find RGB GLX visual or fbconfig

```
Tried to run glxspheres64 without Virtualgl, and got:

```
$ /opt/VirtualGL/bin/glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
ERROR in line 619:
Could not obtain RGB visual with requested properties
```

Then tried with virtualgl:

```
$ vglrun /opt/VirtualGL/bin/glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: r600
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
8.111017 frames/sec - 22.082551 Mpixels/sec
8.139361 frames/sec - 22.159719 Mpixels/sec
8.139943 frames/sec - 22.161305 Mpixels/sec
8.134129 frames/sec - 22.145476 Mpixels/sec
8.117028 frames/sec - 22.098916 Mpixels/sec
8.127523 frames/sec - 22.127491 Mpixels/sec
8.094146 frames/sec - 22.036620 Mpixels/sec
8.082994 frames/sec - 22.006258 Mpixels/sec
8.120539 frames/sec - 22.108475 Mpixels/sec
8.124676 frames/sec - 22.119740 Mpixels/sec
8.072273 frames/sec - 21.977069 Mpixels/sec
8.103361 frames/sec - 22.061709 Mpixels/sec
8.078328 frames/sec - 21.993555 Mpixels/sec
```
So I compiled mesa (http://www.turbovnc.org/Documentation/Mesa) and ran without Virtualgl:

```
$ LD_LIBRARY_PATH=/home/vnc/Downloads/mesa-10.5.4/lib /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x68
Context is Direct
OpenGL Renderer: Mesa X11
Segmentation fault (core dumped)

```
With Mesa with Virtualgl:

```
$ LD_LIBRARY_PATH=/home/vnc/Downloads/mesa-10.5.4/lib vglrun /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Segmentation fault (core dumped)

```
How can one upgrade to the same version like that of Server? Thanks!

**Comment by dcommander** [comment]
Your terminology doesn't make sense.  Please restate the problem using accepted terminology:

* **TurboVNC Server** -- the TurboVNC software that runs on the server end of the connection.  This software consists of a virtual X.org server, a VNC server implementation, and supporting glueware.
* **TurboVNC Server session** or **TurboVNC session** -- a specific running instance of the TurboVNC Server.  Each session represents a separate virtual desktop with its own X display number.  You can have multiple sessions running under the same user account on the same server machine.
* **TurboVNC server machine** or **TurboVNC Server host** or **TurboVNC host** -- the machine on which the TurboVNC Server is installed and on which TurboVNC sessions are started.
* **TurboVNC Viewer** -- the TurboVNC software that runs on the client end of the connection.
* **VNC connection** or **RFB connection** -- a specific connection between a VNC viewer instance on one machine and a VNC server session on another machine.  You can have multiple connections per session, and you can mix & match different implementation of VNC.
* **TurboVNC client** or **TurboVNC client machine** -- the machine on which a particular TurboVNC Viewer instance is running.

It is unclear where you are attempting to run `glxinfo` or `glxspheres` in each case you list above.  Please specify whether you are running on the local display or in a TurboVNC session and on which machine.

Expectations:
* Running GLX applications in TurboVNC without doing anything else is not expected to work at all.
* Using VirtualGL with Mesa Gallium is not expected to work properly.
* Using Mesa with the X11 driver in TurboVNC-- **without** VIrtualGL-- is expected to work.  So actually, if I understand your message above, that segfault is really the only issue here.

**Comment by zenny** [comment]
@dcommander Thanks for elaborating technical jargons of TurboVNC. Let me restate the problem once again in the standard terminology as far as I can.

§1. I am running both TurboVNC server and TurboVNC client session in the same machine with Ubuntu 14.04.3 Trusty.

# IN TURBOVNC SERVER HOST:

§2. The TurboVNC Server host shows:

```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD CAICOS
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

§3. A TurboVNC server session was started with:

```
/opt/TurboVNC/bin/vncserver -geometry 3840x2160 -noreset -nolisten tcp +extension GLX +extension RANDR +extension RENDER -dpi 128
```
The above started a display on MACHINE-GA-970A-D3:2

§4. A TurboVNC client session was started to connect to §3 above with:

```
/opt/TurboVNC/bin/vncviewer MACHINE-GA-970A-D3:2 -DesktopSize=Server -Scale=50

```
# IN TURBOVNC CLIENT SESSION

§5. In the TurboVNC client session as described in §4, tried to run obs-studio (https://github.com/jp9000/obs-studio) which runs fine in the TurboVNC Server host:

```
$ obs
error: Failed to initialize video:  Unspecified error
```
```
$ vglrun obs
error: Failed to initialize video:  Unspecified error

```
in both instances as reported at https://obsproject.com/forum/threads/cant-start-obs-failed-to-initialize-video-unspecified-error.18925/page-2#post-101552 which stated the requirements which is satisfied in the TurboVNC server host as stated in §2 above.

§6. Therefore, I checked in the TurboVNC Client session with and without vglrun as in §4:

```
$ glxinfo | grep OpenGL
Error: couldn't find RGB GLX visual or fbconfig
Error: couldn't find RGB GLX visual or fbconfig

```
Read many a issues exactly like above all over the Internet, but none helped to overcome the issue. 

https://startpage.com/do/search?cat=web&cmd=process_search&language=english&query=Error%3A+couldn%27t+find+RGB+GLX+visual+or+fbconfig+turbovnc&ff=

```
$ vglrun glxinfo | grep OpenGL
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: r600
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL extensions:
```

§7. Then I trie to get OpenGL benchmark inside TurboVNC client session as of §4.

```
$ /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
ERROR in line 619:
Could not obtain RGB visual with requested properties
```
```
$ vglrun -sp +pr /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
***libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: r600***
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
Readback    -  112.74 Mpixels/sec-   41.59 fps
7.985258 frames/sec - 21.645095 Mpixels/sec
Blit        -  173.14 Mpixels/sec-   63.88 fps
Total       -   21.69 Mpixels/sec-    8.00 fps
Readback    -  113.12 Mpixels/sec-   41.73 fps
7.940052 frames/sec - 21.522558 Mpixels/sec
Blit        -  185.01 Mpixels/sec-   68.25 fps
Total       -   21.43 Mpixels/sec-    7.91 fps
Readback    -  112.28 Mpixels/sec-   41.42 fps
7.886805 frames/sec - 21.378226 Mpixels/sec
Blit        -  170.31 Mpixels/sec-   62.83 fps
Total       -   21.46 Mpixels/sec-    7.92 fps
Readback    -  112.99 Mpixels/sec-   41.68 fps
7.967039 frames/sec - 21.595711 Mpixels/sec
Blit        -  188.95 Mpixels/sec-   69.71 fps
Total       -   21.54 Mpixels/sec-    7.95 fps
```

§8. Based on above, I checked whether relevant dri package was installed and it was there:

```
$ dpkg -l | grep ii | grep libgl1
ii  libgl1-mesa-dev                            10.1.3-0ubuntu0.5                                           amd64        free implementation of the OpenGL API -- GLX development files
ii  libgl1-mesa-dri:amd64                      10.1.3-0ubuntu0.5                                           amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-dri:i386                       10.1.3-0ubuntu0.5                                           i386         free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                      10.1.3-0ubuntu0.5                                           amd64        free implementation of the OpenGL API -- GLX runtime
ii  libgl1-mesa-glx:i386                       10.1.3-0ubuntu0.5                                           i386         free implementation of the OpenGL API -- GLX runtime
```
§9.  Finally, I compiled mesa (http://www.turbovnc.org/Documentation/Mesa) and ran without Virtualgl:
```
$ LD_LIBRARY_PATH=/home/vnc/Downloads/mesa-10.5.4/lib /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x68
Context is Direct
OpenGL Renderer: Mesa X11
Segmentation fault (core dumped)
```
With virtualgl:
```
$ LD_LIBRARY_PATH=/home/vnc/Downloads/mesa-10.5.4/lib vglrun /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Segmentation fault (core dumped)
```
Also tried to run obs:

$ LD_LIBRARY_PATH=/home/vnc/Downloads/mesa-10.5.4/lib vglrun obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Default.qss
Attempted path: /usr/share/obs/obs-studio/themes/Default.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
info: Processor: 4 logical cores
info: Processor: AMD Phenom(tm) II X4 965 Processor
info: Physical Memory: 32174MB Total
info: Kernel Version: Linux 3.13.0-70-generic
info: Distribution: "Ubuntu" "14.04"
QObject::connect: invalid null parameter
info: OBS 0.12.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
	buffering (ms):  1000
Segmentation fault (core dumped)

```
All above instances segfaulted.

§10. So I checked whether the libraries did exist in the library path as in §9, and the did:

```
$ ls -l /home/vnc/Downloads/mesa-10.5.4/lib
total 29576
drwxrwxr-x 2 vnc vnc     4096 Dec  3 11:53 gallium
lrwxrwxrwx 2 vnc vnc       15 Dec  3 11:53 libEGL.so -> libEGL.so.1.0.0
lrwxrwxrwx 2 vnc vnc       15 Dec  3 11:53 libEGL.so.1 -> libEGL.so.1.0.0
-rwxrwxr-x 2 vnc vnc   447748 Dec  3 11:53 libEGL.so.1.0.0
lrwxrwxrwx 2 vnc vnc       14 Dec  3 11:53 libGL.so -> libGL.so.1.6.0
lrwxrwxrwx 2 vnc vnc       14 Dec  3 11:53 libGL.so.1 -> libGL.so.1.6.0
-rwxrwxr-x 2 vnc vnc 29828897 Dec  3 11:53 libGL.so.1.6.0
```

Thus, the obs cannot be run inside a TurboVNC client session as stated above in §5 and §10 due to the OpenGL version incompatibility as described in §6 against §2.

Thanks!

**Comment by dcommander** [comment]
* There isn't such a thing as a "TurboVNC client session".  I assume you mean a TurboVNC Viewer instance connecting to a TurboVNC Server session.
* As I said, running GLX applications in a TurboVNC session without doing anything else is *not expected to work* at all.
* As I said, using VirtualGL with Mesa Gallium is *not expected to work properly*.

Thus, on your particular system, the *only* solution that is expected to work properly here is §9.  Every other issue is due to a misunderstanding of the solution.  So let's focus on §9.  Why is Mesa with the X11 driver segfaulting?

How did you build Mesa?  When I build 10.5.4 with:

cd Mesa-*
autoreconf -fiv
./configure --enable-xlib-glx --disable-dri --with-gallium-drivers=swrast
make

Further advice:
* You have a tendency to "get creative" and add things to your command lines that have *not* been instructed.  For instance, adding `+extension GLX +extension RANDR +extension RENDER` to the `vncserver` command line isn't going to do anything.  Please follow the instructions as specified in the User's Guide, or any additional instructions I give you, and do not depart from these instructions while you are asking for tech. support.  Otherwise, I have no way of knowing whether the issue is due to you "getting creative" or whether it is a genuine bug or whether it is a problem with our documentation.  In short, please stop creating a moving target.
* You have a tendency to specify multiple issues in a single issue report.  Please don't do that.  Focus on one issue at a time instead of rapid-firing multiple issues at me.  TurboVNC and VirtualGL have thousands of users worldwide, including in very large corporations and research institutions.  I welcome bug reports, but please realize that if there was something fundamentally wrong with these solutions, then it would be uncovered by one of these large installations.  Thus, a fundamental inability to use the solution is most likely going to be due to user error or attempting to do something with it for which it was never designed.  I've been maintaining these projects for a living since 2004.  That is enough history for me to be able to make such generalizations without being arrogant.

**Comment by zenny** [comment]
> running GLX applications in a TurboVNC session without doing anything else is not expected to work at all.

Can you elaborate what 'extra' is needed to be done?

Actually there was no such problem when I launch the same application in Xpra in th same os environment in the same hardware except slow rendering, fyi.


```
cd Mesa-*
autoreconf -fiv
./configure --enable-xlib-glx --disable-dri --with-gallium-drivers=swrast
make`
```
Did verbatim! (rebuilding again with the latest dev version)

> For instance, adding +extension GLX +extension RANDR +extension RENDER to the vncserver command line isn't going to do anything. 

Tried first with '$ /opt/TurboVNC/bin/vncserver -geometry 3840x2160' but when I saw glx related errors, I consulted man pages and added further parameters to check whether that is not causing the error. But things haven't changed.

**Comment by dcommander** [comment]
Yes, I understand that everything worked fine in xpra (except that it didn't, or otherwise you wouldn't have asked me for support in the first place.)  xpra is a different type of solution.  It is essentially like using remote X but with protocol compression.  I'm not sure whether it uses software OpenGL or whether, like remote X, it forwards all of the OpenGL commands to the client machine to be rendered there, but regardless, it isn't going to have good 3D performance for any heavy-hitting 3D applications.  TurboVNC doesn't provide any kind of built-in OpenGL solution, because it is really designed for use with VirtualGL, and VirtualGL is really designed for use with hardware-accelerated 3D drivers.  I would like to add a fallback software OpenGL mode to TurboVNC at some point, just to alleviate this kind of confusion, but it isn't a priority right now.  I can't possibly support every configuration out there.  I'm just one person.  You were never using a supported VirtualGL configuration, even with xpra.

OK, so now back to the Mesa issue.  I pressed "Comment" before I had finished my post, but the issue is that the instructions at http://www.turbovnc.org/Documentation/Mesa don't work properly for Mesa 10 and later.  Mesa 10 and later doesn't create a libGL.so.1 symlink until you install it.  Thus, you need to add a step:

    make install DESTDIR=~/mesa

Then you should be able to do

    LD_LIBRARY_PATH=~/mesa/usr/local/lib /opt/VirtualGL/bin/glxspheres64

but, of course, the performance is going to be slow there as well, because you're using software OpenGL.  The ultimate solution to this is going to be using a supported GPU and driver configuration with VirtualGL.  If you're running a Radeon, then you should be able to use AMD's Catalyst or Crimson driver, and if you encounter issues with that driver in VirtualGL, I can definitely support that.  But I cannot support VirtualGL with any kind of Mesa driver on the back end.

**Comment by zenny** [comment]
Enlightening! :D

**Comment by totaam** [comment]
> Yes, I understand that everything worked fine in xpra (except that it didn't, or otherwise you wouldn't have asked me for support in the first place.) xpra is a different type of solution. It is essentially like using remote X but with protocol compression.
No, it isn't. Maybe you're thinking of NX.
When it comes to rendering, it is much more like VNC solutions: xpra is a compositing window manager, an X11 client, it just grabs window contents using XComposite + XDamage instead of capturing the whole display as one area like VNC does.

> I'm not sure whether it uses software OpenGL or whether, like remote X, it forwards all of the OpenGL commands to the client machine to be rendered there,
Xpra uses software OpenGL as fallback, or hardware thanks to VirtualGL.

> but regardless, it isn't going to have good 3D performance for any heavy-hitting 3D applications.
That's also incorrect, thanks to VirtualGL!

More information here:
http://xpra.org/trac/wiki/Usage/OpenGL

Cheers
Antoine
(xpra maintainer)

**Comment by dcommander** [comment]
I was thinking of NX.  Sorry for the confusion.
