### ISSUE TITLE
"vglrun xterm" errors (2.5 beta1)

### ISSUE THREAD

**Issue by loganmc10** [VirtualGL/virtualgl#14]
This may not be considered a bug (because you generally wouldn't need to run "vglrun xterm"), so feel free to close this if this is expected behaviour:

when I run "vglrun xterm", I get these errors:
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded: ignored.

I have both the 32-bit and 64-bit RPM's installed. I've tested this on RHEL6 and RHEL7 and it happens for both.

xterm is the only program I can see this in, I can run "vglrun ls", "vglrun gedit", etc... with no error messages, I only see it with "vglrun xterm"

If I set LD_PRELOAD to /usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so, these errors don't appear. But it does happen even with just the 64-bit RPM installed.

**Comment by dcommander** [comment]
https://cdn.rawgit.com/VirtualGL/virtualgl/2.5beta1/doc/index.html#hd0012

**Comment by loganmc10** [comment]
Are you sure this is the same thing?

When I do a "ls -l /usr/bin/xterm":
-rwxr-xr-x. 1 root root 500488 Jun  9  2014 /usr/bin/xterm (no suid)

As well, it doesn't really explain why this goes away when I set LD_PRELOAD to /usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so.

vglrun xterm:
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded: ignored.

vglrun env LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so xterm:
No error

**Comment by nathankidd** [comment]
On 15-12-19 02:20 PM, Logan McNaughton wrote:
> Are you sure this is the same thing?
>
> When I do a "ls -l /usr/bin/xterm":
> -rwxr-xr-x. 1 root root 500488 Jun 9 2014 /usr/bin/xterm (no suid)

Xterm generally launches /usr/lib/utempter/utempter, which is SUID.

**Comment by dcommander** [comment]
Long and the short of it:  if making the faker libs setuid root doesn't fix this, then please reopen the issue.

As to why running `vglrun env LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so xterm` worked, could it be that LD_PRELOAD wasn't actually communicated into the xterm?  Perhaps it needs to be exported?  Otherwise, I have no explanation.

**Comment by loganmc10** [comment]
Adding u+s to the faker fixed the problem, I tried to delete my previous comment before I looked foolish, but alas, I was too late.

The vglrun env .... trick does work though, try to launch gnome/mate-session or glxgears that way in TurboVNC and you'll see that it works properly (and it does have the effect of suppressing the xterm errors).

**Comment by dcommander** [comment]
Weird.  I guess there is some fundamental difference between launching a program with `env LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so {program}` and launching it with `export LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so; exec {program}`.  Curiosity will probably get the better of me, and I'll eventually figure out why, but not today.

**Comment by dcommander** [comment]
Upon further investigation, the reason why the error message went away is that you specified absolute pathnames in LD_PRELOAD.  You can achieve the same effect by editing vglrun and prepending "/usr/lib64" to all of the faker library names.  However, this isn't actually fixing the underlying problem.  It's simply disabling the error message.  Per the description of LD_PRELOAD:  "For set-user-ID/set-group-ID ELF binaries, preload pathnames containing slashes are ignored, and libraries in the standard search directories are loaded only if the set-user-ID permission bit is enabled on the library file."  So when you set LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so and attempt to run xterm, LD_PRELOAD is ignored, so you never see an error message.  When you set LD_PRELOAD=libdlfaker.so:libvglfaker.so, then LD_PRELOAD is not ignored, the linker tries to find libdlfaker.so and libvglfaker.so in the search path, and if it sees that those libraries aren't setuid or they aren't in /usr/lib64 or /lib64, it prints the error message and refuses to preload them.

Long and the short of it:  In order to load VGL into a setuid binary, the VGL libraries have to be setuid.  However, in the case of xterm, you don't actually need VirtualGL to be loaded into the xterm binary itself.  You just need the LD_PRELOAD environment variable to be set so that applications you launch from within xterm will have VirtualGL loaded into them.  So if none of the 3D applications you want to run are setuid, then it is sufficient to `vglrun xterm` and ignore the error messages.  The LD_PRELOAD environment variable will still be set within the xterm session.

**Comment by loganmc10** [comment]
Ok good to know, thanks for looking into that.
