### ISSUE TITLE
Problem with library and LD_LIBRARY_PATH under vglrun

### ISSUE THREAD

**Issue by halowine** [VirtualGL/virtualgl#143]
Hello,

(This thread has already be sent 3 weeks ago but I made a mistake, it’s vglrun the application that creates a problem not vglconnect. Note that we still have the issue)

I’m trying to launch an application through vglrun but my app fails to open. I think the problem comes from the LD_LIBRARY_PATH.
My application need shared library path that I set in LD_LIBRARY_PATH. If I activate the verbose in vglrun (vglrun +v), I see that it’s resetting the LD_LIBRARY_PATH variable at startup :

NOTICE: Added /usr/lib64 to LD_LIBRARY_PATH

The problem is that my application crashes because it looks for the library in /usr/lib64 first before my /shared_path. The library is the libz.so and my system have old libz.so which lead to the crash. The correct libz.so version is in /shared_path.

Is there a way to avoid the resetting of LD_LIBRARY_PATH at startup? Or to control the LD_LIBRARY_PATH afterward ?

In order to work, my LD_LIBRARY_PATH should be:
LD_LIBRARY_PATH=/shared_lib:/usr/lib64
But vglrun forces:
LD_LIBRARY_PATH=/usr/lib64:/shared_lib:/usr/lib64

Thank you

**Comment by dcommander** [comment]
Our official packages do not set `LD_LIBRARY_PATH`. You are apparently using a custom build or package. With custom builds, a script (**.vglrun.vars64**) is installed into the same directory as **vglrun**. That script, if present, will prepend the directory containing the VGL faker libraries to `LD_LIBRARY_PATH`, but such is unnecessary if the faker libraries are installed under **/usr/lib64** (which is why our official packages don’t include **.vglrun.vars64**.) The easiest solution is to simply delete **.vglrun.vars64** from the binary directory.
