### ISSUE TITLE
VirtualGL not working in multi-user mode under Ubuntu 20.04 - fatal Ubuntu issues?

### ISSUE THREAD

**Issue by fusentasticus** [VirtualGL/virtualgl#151]
So my considerations in #150 were premature.  It is true that a session from a client to a 20.04 Ubuntu host configured with virtualgl (and `/etc/gdm3/custom.conf`  updated with `WaylandEnable=false`) allows 3D graphic card rendering with the following steps:
```
(client, start ssh) vglconnect glowstick-ubuntu.local 
(host, within ssh) VGL_ICON=1 VGL_DISPLAY=:1 vglrun glxgears
```
This is *while the physical console of the Ubuntu host is used by a user in standard gnome session*, but it holds *only* if the user (_user_host_) logged on at the console is the same as the user (_user_client_, `fusentasticus` above) vlgconnecting from the client. Otherwise, with different users, the following happens:
```
fusentasticus@glowstick-ubuntu:~$ VGL_ICON=1 VGL_DISPLAY=:1 vglrun glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    10.0.0.18, the IP address of your SSH client.
[VGL] ERROR: OpenGL error 0x0502
[VGL] ERROR: in readPixels--
[VGL]    470: Could not Read Pixels
```
Same  0x0502 crash for `VGL_DISPLAY=:0`.  

Q1: So how do I fix this? (I believe I am re-reporting the observations in https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-678830029)

So I'll be happy with a workaround for my setup that forces the same _user_client_ to be continuously logged on to console. That's because I realize that a fix for the above problem is still not a fix for the [ouch?](https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-671478235):
> Best practices are to not allow local logins on the 3D X server

Q2:  Is this a general limitation of VirtualGL, notwithstanding the complications of Wayland, that is, that console login using the default X server is not recommended?

Throwing in a second lesser graphics card as you suggest in https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-671478235 and configuring it for virtualGL would not be a big deal --- if it's easy to configure. 

Q3: Would you have helpful links for that?

**Comment by dcommander** [comment]
> So my considerations in #150 were premature. It is true that a session from a client to a 20.04 Ubuntu host configured with virtualgl (and `/etc/gdm3/custom.conf` updated with `WaylandEnable=false`) allows 3D graphic card rendering with the following steps:
> 
> ```
> (client, start ssh) vglconnect glowstick-ubuntu.local 
> (host, within ssh) VGL_ICON=1 VGL_DISPLAY=:1 vglrun glxgears
> ```
> 
> This is _while the physical console of the Ubuntu host is used by a user in standard gnome session_, but it holds _only_ if the user (_user_host_) logged on at the console is the same as the user (_user_client_, `fusentasticus` above) vlgconnecting from the client. Otherwise, with different users, the following happens:
> 
> ```
> fusentasticus@glowstick-ubuntu:~$ VGL_ICON=1 VGL_DISPLAY=:1 vglrun glxgears
> [VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
> [VGL]    10.0.0.18, the IP address of your SSH client.
> [VGL] ERROR: OpenGL error 0x0502
> [VGL] ERROR: in readPixels--
> [VGL]    470: Could not Read Pixels
> ```
> 
> Same 0x0502 crash for `VGL_DISPLAY=:0`.
> 
> Q1: So how do I fix this? (I believe I am re-reporting the observations in [#129 (comment)](https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-678830029))

In general, using the 3D X server simultaneously for VirtualGL and local logins is not a supportable configuration.  The problem isn't just access.  The problem is also that the X server will reset when the local user logs out, and that will have the effect of aborting any applications that are currently running with VirtualGL.

The local user could, of course, use `xhost` to grant permissions to all other users of the machine, but of course that is also a security nightmare.  Nothing would prevent those other users from monitoring everything that the local user does, including snooping password entries and taking screenshots and even hijacking the session (using x11vnc, for instance.)  In fact, nothing would prevent VGL users from doing that when the 3D X server is at the login prompt, either, which is yet another reason why local logins are ill-advised on a VGL server unless it truly is a single-user machine (i.e. unless you're using VGL to access your own personal workstation.)

The supported configuration is to leave the 3D X server at the login prompt and run `vglserver_config` to manage access to it.  If you insist on being able to use VirtualGL simultaneously with local logins on a multi-user machine, then your only recourses are:

1. Get a second GPU (perhaps lower-spec) and run a separate X server on it that is dedicated to local logins.
2. Use the EGL back end in the evolving 3.0 pre-release builds: https://virtualgl.org/DeveloperInfo/PreReleases.  That is currently only known to work with nVidia hardware and their proprietary drivers.

> So I'll be happy with a workaround for my setup that forces the same _user_client_ to be continuously logged on to console. That's because I realize that a fix for the above problem is still not a fix for the [ouch?](https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-671478235):
> 
> > Best practices are to not allow local logins on the 3D X server
> 
> Q2: Is this a general limitation of VirtualGL, notwithstanding the complications of Wayland, that is, that console login using the default X server is not recommended?

See above.  It has always been problematic.  "Back in the day" (i.e. when I was developing VirtualGL and TurboVNC for my previous corporate employers), you could get away with it, but only by opening up the X server to all users of the machine (which has very negative security ramifications.)  Then display managers started resetting the X server when the local user logged out.  Then, with Wayland, they started using a separate X connection for the display manager and local session.  The inability to use VGL with multiple users while a local user is logged in is a recent limitation of the display manager, not of VirtualGL, but using VGL with multiple users while a local user is logged in has never been recommended.

> Throwing in a second lesser graphics card as you suggest in [#129 (comment)](https://github.com/VirtualGL/virtualgl/issues/129#issuecomment-671478235) and configuring it for virtualGL would not be a big deal --- if it's easy to configure.
> 
> Q3: Would you have helpful links for that?

Sorry, I don't.  It would involve the multi-seat capability of GDM or whatever display manager you are using.  I don't really understand why you need to log in locally anyhow, unless the machine is your personal workstation.  And if it's your personal workstation, why do you need to grant other users access?  That isn't a normal VGL configuration.  Most commonly, VGL is installed on "big iron" servers with dedicated headless 3D X servers that no one can log into.  If you have a specific business need for a server that allows simultaneous multi-user VGL usage and local logins, then I am happy to help you configure that ... for a price.  Contact me offline if you want to pursue that consulting relationship.  Otherwise, you are working outside of what the community or I can support.

**Comment by fusentasticus** [comment]
Very helpful write-up @dcommander!  The historical context was just what I was missing. So the X server is a giant monster squid that can be the only master of the graphics card (unless you're a major high tech corporation and buy $$$ solutions from Nvidia and such).  This squid has all sorts of other UI stuff baked into it. Therefore you advise to put it on a headless machine where it'll be tamed to take care of the 3D stuff only. I think I got it!

My usage scenario is that of an IT family under COVID 19 where everybody would like their own server class machine (64Gb RAM, two-digit number of CPUs, 8Gb Nvidia card, etc) just for the occasional jobs that require punch, but where buying a handful of such machines is wasteful in terms of capital and running costs.  So, I only have one and making it headless is not really a problem I realize.

Thanks!

**Comment by svargh** [comment]
> to leave the 3D X server at the login prompt and run `vglserver_config` to manage access to it. If you insist on being able to use VirtualGL simultaneously with local logins on a multi-user machine, then your only recourses are:
> 
>     1. Get a second GPU (perhaps lower-sp

Very helpful write-up! Coming from Windows world for sharing a silent workstation with a NVidia RTX 3090, 128GB, Ryzen5950X  with more team members.
I was not aware of this limitation, wasted hours to make it work during Linux migration, might be this should be put in the Docs?

I would like to try out the evolving 3.0  build, and hopefully see some dri files.
[Here ](https://github.com/VirtualGL/virtualgl/runs/2115411497?check_suite_focus=true)I see only deb files  with versioning 2.6:
"upload: ../../../src/vgl.nightly/latest/files/virtualgl_2.6.80_amd64.deb to s3://virtualgl-pr/dev/linux/virtualgl_2.6.80_amd64.deb"
Is this already the evolving 3.0 package?

PS: It would be great, if /dev/dri/* will be offered, I used the dri files from Intel and VMWare for providing desktops without active VT within LXC instances and even in nested LXC instances

**Comment by svargh** [comment]
Ok, I managed to build the dev branch which outputs virtualgl_2.6.80_amd64.deb.
 vglrun -d /dev/dri/card1 glmark2 works!!
hanks  @dcommander for your effort providing the /dev/dri/cardxxx ! This makes my life so much easier! 
(LXC, docker nested LXC,  + console desktop for workstation users)

**Comment by dcommander** [comment]
> Very helpful write-up! Coming from Windows world for sharing a silent workstation with a NVidia RTX 3090, 128GB, Ryzen5950X with more team members.
> I was not aware of this limitation, wasted hours to make it work during Linux migration, might be this should be put in the Docs?

The User's Guide already has a dire warning about local logins:
https://cdn.rawgit.com/VirtualGL/virtualgl/2.6.5/doc/index.html#hd006001

If you're referring to documenting multi-head configurations, those are so system-specific that attempting to document them would be a fool's errand.  `vglserver_config` works fine for the normal VirtualGL use case, which is a dedicated 3D X server that is never used for local logins.  Any esoteric use cases are the responsibility of the user, unless they want to pay me for professional support.  I'd rather spend the limited project resources improving the EGL back end, which will hopefully make all of this moot in the long term.

> I would like to try out the evolving 3.0 build, and hopefully see some dri files.
> [Here ](https://github.com/VirtualGL/virtualgl/runs/2115411497?check_suite_focus=true)I see only deb files with versioning 2.6:
> "upload: ../../../src/vgl.nightly/latest/files/virtualgl_2.6.80_amd64.deb to s3://virtualgl-pr/dev/linux/virtualgl_2.6.80_amd64.deb"
> Is this already the evolving 3.0 package?

See "Versioning Conventions" [here](https://virtualgl.org/DeveloperInfo/PreReleases).  2.6.80 == 3.0 alpha/dev/evolving.  It will become 2.6.90 when it enters beta.
