### ISSUE TITLE
Slow performance without ssh (same machine)

### ISSUE THREAD

**Issue by vojenfr** [VirtualGL/virtualgl#152]
Hello, 

I have installed VirtualGL package on Pop!_OS 20.10 and tested directly with this command:
> vglrun glmark2
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   GeForce RTX 2080/PCIe/SSE2
    GL_VERSION:    4.6.0 NVIDIA 455.38
=======================================================
[build] use-vbo=false: FPS: 562 FrameTime: 1.779 ms
[build] use-vbo=true: FPS: 633 FrameTime: 1.580 ms

and without :
> glmark2 
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   GeForce RTX 2080/PCIe/SSE2
    GL_VERSION:    4.6.0 NVIDIA 455.38
=======================================================
[build] use-vbo=false: FPS: 9005 FrameTime: 0.111 ms
[build] use-vbo=true: FPS: 14156 FrameTime: 0.071 ms
=======================================================

Why only 5~10% of GPU are available,i forgot something ?

**Comment by dcommander** [comment]
GLMark isn't a realistic benchmark for VirtualGL.  It attempts to render a bunch of very small geometries as fast as possible.  I could say the same thing about GLXgears.  The performance difference you observed is due to the overhead of reading back the framebuffer.  However, given that the human eye cannot process more than about 60 frames/second and X11 mouse events are not sampled at more than 100 frames/second, the difference between 500 fps and 10,000 fps is pretty meaningless in real-world interactive 3D application usage.  An application that is actually rendering at 10,000 fps will not "feel" any faster to the user than an application that is actually rendering at 500 fps.  VirtualGL's readback overhead wouldn't amount to that much of a difference with real-world 3D applications anyhow, because the overhead is per-frame rather than per-primitive, so the overhead becomes less visible as the geometry size increases.

In general, it's unreasonable to expect that you'll get exactly the same performance characteristics with a remote display that you get with a local display.  Yes, VirtualGL will cause low-level benchmarks to slow down on a local display, but VirtualGL isn't meant to be used with local displays.  That isn't the point of VirtualGL.  The point is that, without VirtualGL, your only other choice for OpenGL with a remote display is usually software (unaccelerated) OpenGL.  Try running `/opt/VirtualGL/bin/glxspheres64 -p 1000000` with software OpenGL vs. VirtualGL, and I think you'll clearly see the advantage of VirtualGL in that case (on my machine, with a TurboVNC session, it's the difference between 2 fps and 150.)  That same command, when comparing the local display with and without `vglrun`, produces about 100 fps with `vglrun` and 650 fps without, which is still above the limits of human vision.  If you bump up the geometry to 10 million polys (`/opt/VirtualGL/bin/glxspheres64 -p 10000000 -n 200`), the difference becomes 50 fps vs. 100 fps, which might be barely discernible to some users.  Again, however, VirtualGL isn't meant to be used on a local display, so that's not a realistic comparison.

My overall point is that, yes, VirtualGL does introduce some per-frame overhead because it has to read back the framebuffer in order to transport the OpenGL-rendered frames to a remote computer.  That is to be expected, but the readback overhead should not be noticeable in a real-world usage scenario.  In a real-world usage scenario, the end-to-end frame rate will almost always be limited by either the CPUs or the network, not the GPU, which is why we provide [our own high-performance remote desktop software to accompany VirtualGL](https://turbovnc.org).  Note also that one of the impetuses for #9 (deferred readback) is to eliminate the overhead that VGL introduces when it reads back the framebuffer in the application's rendering thread.  But that won't actually affect the aggregate GPU overhead unless you're on a slow network where frame spoiling is occurring.  Otherwise, it would just move the readback overhead into the transport thread, so OpenGL benchmarks would no longer detect it.

Benchmarking a remote display solution is tricky, because you have to understand exactly what you're measuring and why it matters in a real-world application usage scenario.  OpenGL benchmarks are designed to measure the performance of the OpenGL pipeline, but that's only one of several pipelines that exist in a VirtualGL environment.  The rest of the pipelines are pixel pipelines rather than geometry pipelines.  25 years ago, when I was working with very early 3D Labs GPUs (the term "GPU" hadn't even been invented yet-- we just called them "3D accelerators" or "3D graphics cards"), we would sometimes talk about "fill rate limitations" in certain GPUs.  That means that, in certain rendering scenarios, the overall frame rate would be limited by the GPU's ability to draw pixels rather than its ability to render geometry.  That is almost always the case with VirtualGL.  It is almost always fill-rate-limited, so that's why running raw OpenGL geometry benchmarks with VirtualGL isn't particularly useful.
