### ISSUE TITLE
`vglrun` should use the same realpath method as vglserver_config.

### ISSUE THREAD

**Issue by Parakleta** [VirtualGL/virtualgl#159]
I just discovered that `vglrun` also sets a MYPATH variable without using realpath, so this should also be updated as per #147.  This currently prevents `vglrun` from working if it is linked to a different directory (i.e. symbolically linked into /opt/bin for pathing reasons).

**Comment by dcommander** [comment]
The problem with `vglserver_config` was that it used its own invocation path (stored in the `MYPATH` variable) to determine the full pathname of `vglgenkey`, which was then added to the display manager startup script.  Thus, if invoked with a relative path, `vglserver_config` used the same relative path for `vglgenkey`, and that relative path was incorrect within the context of the display manager startup script.

With `vglrun`, `MYPATH` is used only to invoke `.vglrun.vars*`.  The `.vglrun.vars*` scripts are only intended to be used if the faker libraries are not installed somewhere in the dynamic linker path.  For instance, if you install a 64-bit build of VirtualGL under **/opt/vgl** and then invoke `/opt/vgl/bin/vglrun`, `/opt/vgl/bin/vglrun` will in turn invoke `/opt/vgl/bin/.vglrun.vars64`, which in turn adds **/opt/vgl/lib64** to `LD_LIBRARY_PATH`.  If you then symlink `/opt/vgl/bin/vglrun` under **/usr/bin**, the `/usr/bin/vglrun` symlink will not invoke `.vglrun.vars64` unless `.vglrun.vars64` is also symlinked under **/usr/bin**.  That is by design.  It is assumed that, if you symlink `vglrun` under a directory in the `PATH`, you will also install the faker libraries under a directory in the dynamic linker path (as the official VirtualGL packages do) or symlink `.vglrun.vars*` under the same directory as `vglrun`.

Thus, you have four options:
1. Install VirtualGL executables/scripts (`VGL_BINDIR`) into a directory in the `PATH` (e.g. **/usr/bin**) and VirtualGL faker libraries (`VGL_LIBDIR`) into a directory in the dynamic linker path (e.g. **/usr/lib64**.)  In this case, the `.vglrun.vars*` scripts are unnecessary but innocuous.
2. Install VirtualGL executables/scripts (`VGL_BINDIR`) into a directory not in the `PATH` (e.g. **/opt/VirtualGL/bin**) and VirtualGL faker libraries (`VGL_LIBDIR`) into a directory in the dynamic linker path (e.g. **/usr/lib64**), and symlink `vglrun` under a directory in the `PATH` (e.g. **/usr/bin**.)  In this case, the `.vglrun.vars*` scripts are unnecessary but innocuous.  (This is what the official VirtualGL packages do.)
3. Install VirtualGL executables/scripts (`VGL_BINDIR`) into a directory not in the `PATH` (e.g. **/opt/VirtualGL/bin**) and VirtualGL faker libraries (`VGL_LIBDIR`) into a directory not in the dynamic linker path (e.g. **/opt/VirtualGL/lib64**.)  In this case, the `.vglrun.vars*` scripts are necessary. 
4. Install VirtualGL executables/scripts (`VGL_BINDIR`) into a directory not in the `PATH` (e.g. **/opt/VirtualGL/bin**) and VirtualGL faker libraries (`VGL_LIBDIR`) into a directory not in the dynamic linker path (e.g. **/opt/VirtualGL/lib64**), and symlink `vglrun` under a directory in the `PATH` (e.g. **/usr/bin**.)  In this case, the `.vglrun.vars*` scripts should also be symlinked under the same directory that contains the `vglrun` symlink.

If any of those four options does not work, then I would consider that to be a bug.  However, what you seem to be asking for is Option 4 with modifications to make the `/usr/bin/vglrun` symlink find `.vglrun.vars*` under a directory other than **/usr/bin**.  By design, that isn't supported.  If there is a compelling reason why it should be supported, then make your case.

**Comment by Parakleta** [comment]
I'm not sure I understand the rationale behind the `.vglrun.vars*` files being separate executables as they are.  It seems that they could just be part of `vglrun` directly since they are either required or innocuous.  If your preferred method is to symlink them together I suppose I can work with that.

**Comment by dcommander** [comment]
The rationale is that VirtualGL, by necessity, is managed like an enterprise product as well as an open source project.  The enterprise product, embodied in our official packages, has always installed the fakers under the system library path.  I introduced `.vglrun.vars*` as a non-disruptive means of supporting other installation scenarios.  Since those scripts were introduced in a bug-fix release, I did not want to introduce potential bugs into the enterprise product, so it made the most sense to apply the fix only where it is needed.  Personally, I would prefer that `vglrun` not override `LD_LIBRARY_PATH`, because I like to point `LD_LIBRARY_PATH` to my VirtualGL build directory for testing purposes.  Also, the official packages are built with `VGL_LIBDIR=/opt/VirtualGL/lib`, but the packaging system moves the library directory when the packages are created.  (This is because Debian-based and RPM-based systems use different system library paths, and for 32-bit builds, it is necessary to use a different system library path for the .deb package used on i386 systems vs. the .deb package used as a 32-bit supplement for amd64 systems.)  Thus, the `.vglrun.vars*` scripts actually wouldn't be innocuous in the official packages.  You can file all of this under "historical reasons." The underlying problem is that:

1. Different distributions like to install things in different places.
2. VirtualGL's official packages are designed to be cross-distribution, so the build-time and run-time distribution aren't necessarily the same.
3. In the case of 32-bit builds, it is necessary to generate two different types of .deb packages with different library paths using the same build directory.

There are other ways of solving the problem, but it would take a lot of time (==money) to revisit my solution, and I don't have the resources right now.  Eliminating `.vglrun.vars*` would require not only a build and packaging system overhaul but also an overhaul of our official build scripts, and it would likely require performing a separate build for every package we generate (which would increase the build time for CI builds, which is not desirable.)

**Comment by Parakleta** [comment]
I really appreciate the detailed answer. Thank you.

**Comment by dcommander** [comment]
No problem.  Answering questions like this gives me an opportunity to revisit old assumptions.
