### ISSUE TITLE
Application crashes using EGL

### ISSUE THREAD

**Issue by firefly-serenity** [VirtualGL/virtualgl#171]
VritualGL Version: 2.6.90
Xpra Version 4.2

I am trying to launch animator4 with xpra and virtualgl (and EGL) like so:

`xpra start --bind-tcp=some-host:some-port --start="vglrun -ge -d /dev/dri/card1 a4"`

Unfortunately the application crashes at some point and the logs show the following:

```
[VGL] ERROR: Could not open libxcb-keysyms
[VGL]    libxcb-keysyms.so.1: cannot open shared object file: No such file or directory
[VGL] ERROR: in eglMakeCurrent()--
[VGL]    43: EGL_BAD_ACCESS
QObject::~QObject: Timers cannot be stopped from another thread
/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py:1612: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
```

I'm not entirely sure if the resulting error is indeed related to virtualgl but I still wanted to report it here in case it is a bug that can be fixed easily.

**Comment by firefly-serenity** [comment]
Ok it is pretty obvious, I needed to install xcb-util-keysyms to get rid of the VGL errors. Might be worth putting it as dependency into the rpm file. BTW: I'm using CentOS 8.4

**Comment by dcommander** [comment]
There is no dependency because the  XCB libraries are not a hard requirement for VirtualGL. They are needed only when running applications that use XCB-GLX. I suspect that A4 would have failed without VirtualGL as well. If not, then the real issue is that VGL requires certain XCB libraries that not all XCB-GLX applications require. Otherwise, VGL cannot be held responsible if the necessary dependencies to run a 3D application are not installed.
