### ISSUE TITLE
question for clarification: glxinfo warning re: true color

### ISSUE THREAD

**Issue by karlkleinpaste** [VirtualGL/virtualgl#183]
Experimenting for the first time with EGL back end. Generally things seem to be working fine. I'm mystified by this diagnostic from `glxinfo`:
```
[VGL] Opening EGL device egl
[VGL] WARNING: VirtualGL attempted and failed to obtain a true color visual on
[VGL]    the 3D X server egl suitable for off-screen rendering.
[VGL]    This is normal if the 3D application is probing for visuals with
[VGL]    certain capabilities, but if the application fails to start, then make
[VGL]    sure that the 3D X server is configured for true color and has
[VGL]    appropriate GPU drivers installed.
```
It happens on 6 machines that I've upgraded, with a variety of modern nvidia devices and driver either 470 or 495. Is this any source of concern, or is it indicative of any aspect of misconfiguration on my part?

**Comment by dcommander** [comment]
That definitely shouldn’t happen and doesn’t happen on my test machines (one of which is also running 470.xx.) Please send me the output of:

`xdpyinfo`

`glxinfo` (without `vglrun`. I want to see the OpenGL specs from the 2D X server.)

from one of the failing machines. Also please specify the operating system and what kind of 2D X server you are using when you observe the failures.

**Comment by karlkleinpaste** [comment]
Fedora 34 (5.14.18-200.fc34.x86_64), driver 470.74, TurboVNC 2.2.6.
[glxinfo.txt](https://github.com/VirtualGL/virtualgl/files/7576682/glxinfo.txt)
[xdpyinfo.txt](https://github.com/VirtualGL/virtualgl/files/7576683/xdpyinfo.txt)

**Comment by dcommander** [comment]
Follow-up questions:
- Does the issue occur both with VirtualGL’s implementation of glxinfo (under **/opt/VirtualGL/bin**) and the system’s implementation (under **/usr/bin**)?
- Can you post the output from the failing application when run with `vglrun +tr +v`?

**Comment by karlkleinpaste** [comment]
Yes, both instances of glxinfo.
[vglrun.tr.v.glxinfo.txt](https://github.com/VirtualGL/virtualgl/files/7576753/vglrun.tr.v.glxinfo.txt)

**Comment by dcommander** [comment]
Easily reproducible, as it turns out.  I just didn't see the warning during my testing of the EGL back end because I wasn't running in verbose mode.  I will investigate.

**Comment by dcommander** [comment]
The warning is completely innocuous.  It was a result of the `mesa_hack()` function in [glxinfo](https://cgit.freedesktop.org/mesa/demos/tree/src/xdemos/glxinfo.c), which isn't relevant for VirtualGL. (I'm not sure if `mesa_hack()` is even relevant for modern Mesa releases.  It seems to only be relevant if Mesa was built as a standalone GLX/X11 emulator rather than with DRI.)  In verbose mode, VirtualGL prints a warning the first time `glXChooseVisual()` fails, which occurs in `mesa_hack()` when using the EGL back end because the EGL back end doesn't support accumulation buffers. 395a9c91817313ca0808d51272e5a615f77918ef explains the history behind why VirtualGL prints that warning, but in a nutshell, the warning never should have been printed when using the EGL back end, because it isn't relevant to the EGL back end.  395a9c91817313ca0808d51272e5a615f77918ef silences the warning when using the EGL back end, and ffe6732d5cb49b349160faf3e7e11b84799fd89c modifies our version of glxinfo so that its implementation of `mesa_hack()` doesn't try to choose a visual with accumulation buffers.
