### ISSUE TITLE
Only one vglrun works on a shared node with multiple GPUs 

### ISSUE THREAD

**Issue by luop0812** [VirtualGL/virtualgl#193]
I need to set up VirtualGL on nodes with multiple Nvidia GPUs in a cluster. The nodes are shared and managed by the SLURM batch scheduler. If two jobs happened to be scheduled on the same node, each job will have its own GPU device and the X server can only be started on that GPU. This is enforced by Linux Cgroup. The problem is only one job can execute `vglrun` to launch an application. The vglrun started later will make the vglrun stared earlier terminated with the following error:

[VGL] ERROR: OpenGL error 0x0502
[VGL] ERROR: in readPixels--
[VGL]    435: Could not read pixels

Any idea how to fix this?

**Comment by karlkleinpaste** [comment]
Do you need an X server at all? In VGL 3, use `vglrun -d /dev/dri/cardX` to pick a specific GPU, especially since you say each job will have its own.

**Comment by luop0812** [comment]
I tried `vglrun -d /dev/dri/cardX`. But for one of the applications I tested, the images were corrupted. My understanding is that this approach is using the EGL backend, which maybe because at the moment "the EGL back end does not yet support all of the GLX extensions and esoteric OpenGL features that the GLX back end supports."([from VirtualGL User Guide](https://rawcdn.githack.com/VirtualGL/virtualgl/main/doc/index.html#hd002001))
That's why I switched back to the GLX backend, which needs an X server and then I came into the problem when two jobs are running on the same node and both need 3D hardware acceleration.

**Comment by dcommander** [comment]
@luop0812 I don't fully understand your configuration.  Are you trying to start 3D X servers on demand?  That isn't generally now VirtualGL works.  The 3D X server is supposed to always be running in the background, and it is shared by multiple VirtualGL users.  Multiple GPUs are generally attached to different screens on the same 3D X server, so they can be addressed with `vglrun -d :0.0`, `vglrun -d :0.1`, etc.  I will note that OpenGL error 0x0502 (`GL_INVALID_OPERATION`) is the same error that occurs when the 3D X server isn't the active virtual terminal.  You may be able to work around it by configuring the 3D X server to be headless (https://virtualgl.org/Documentation/HeadlessNV). 

As far as the EGL back end, is the application you tested freely available?  If so, I would like to diagnose why it is failing with the EGL back end.  That is the only way that I can improve the EGL back end so that issues like that do not occur in the future.

**Comment by luop0812** [comment]
@dcommander Yes, I am trying to start 3D X servers on demand in a SLURM cluster where nodes are shared. The work around didn't fix the problem. I still got the same error. 

I saw something interesting in the log file of the X servers. So when the X server was started in a job, it tried to launch X on each of the four GPUs on the node, but only succeeded on the GPU the job was allocated. If the device is GPU-0, it kept GPU-0 and deleted all other GPUs. If the device is not GPU-0, it renamed that GPU device to GPU-0 and then deleted all other GPUs. In both cases, the physical graphic device became GPU-0 in the X server. Would this be the reason why the second vglrun kicked out the first vglrun?
```
(II) NVIDIA(GPU-1): Deleting GPU-1
(II) NVIDIA(GPU-2): Renaming GPU-2 to GPU-1
(II) NVIDIA(GPU-3): Renaming GPU-3 to GPU-2
(II) NVIDIA(GPU-1): Deleting GPU-1
(II) NVIDIA(GPU-2): Renaming GPU-2 to GPU-1
(II) NVIDIA(GPU-1): Deleting GPU-1
```
```
(II) NVIDIA(GPU-0): Deleting GPU-0
(II) NVIDIA(GPU-1): Renaming GPU-1 to GPU-0
(II) NVIDIA(GPU-2): Renaming GPU-2 to GPU-1
(II) NVIDIA(GPU-3): Renaming GPU-3 to GPU-2
(II) NVIDIA(GPU-0): Deleting GPU-0
(II) NVIDIA(GPU-1): Renaming GPU-1 to GPU-0
(II) NVIDIA(GPU-2): Renaming GPU-2 to GPU-1
(II) NVIDIA(GPU-1): Deleting GPU-1
```
The complete log files can be found [here](https://github.com/luop0812/Xserver-logs)

The application I mentioned is paid software.

**Comment by luop0812** [comment]
@dcommander I also uploaded my [xorg.conf](https://github.com/luop0812/Xserver-logs/blob/main/xorg.conf). Is this problem resolvable?

**Comment by dcommander** [comment]
It appears that your xorg.conf is trying to use all of the GPUs.  Surely that isn't what you want if you are starting 3D X servers on demand?  I assume you would want each 3D X server to work with only a single GPU?

I honestly don't know if the problem is resolvable.  Starting 3D X servers on demand is not an officially supported configuration for VirtualGL.  If you or someone else in the community can make it work, great, but I can provide only cursory assistance with this outside of a [paid support arrangement](https://virtualgl.org/About/ProfessionalServices).

**Comment by dcommander** [comment]
@luop0812 Let me explain what is possible, maybe possible, and not possible.

#### Possible
- Using a single 3D X server on the machine, and configuring each screen of the 3D X server to use a different GPU

    This allows any job running on the machine to use any GPU, as long as `VGL_DISPLAY` is set to the screen corresponding to the desired GPU (`:0.1`, `:0.2`, etc.)  This also allows multiple jobs to simultaneously share the same GPU.  This is the standard way of configuring VirtualGL, including in grid environments.

#### Maybe Possible
- Starting a 3D X server on demand that exclusively uses one GPU

    This assumes that any given job will only need access to a single GPU and that no other jobs will require simultaneous access to the same GPU.  The idea is that each GPU would have a corresponding **xorg.conf** file, and you would start the 3D X server using the **xorg.conf** file for the GPU that it will use.

#### Not Possible
- Starting multiple 3D X servers that use the same GPU

    This appears to be what you are trying to do.

**Comment by luop0812** [comment]
Thanks @dcommander. The second case is what we want. I have tried to provide an xorg.conf for each GPU and haven't had any luck so far.

**Comment by dcommander** [comment]
Refer to https://www.x.org/archive/X11R6.8.0/doc/xorg.conf.5.html.  You can probably manipulate the `$XORGCONFIG` environment variable to specify a location for it, but note the different behavior when the X server is started as a normal user vs. a root user.
