### ISSUE TITLE
Installing VirtualGL on Cygwin problems

### ISSUE THREAD

**Issue by vsantalov** [VirtualGL/virtualgl#20]
Hello,
It appears the instructions on http://www.virtualgl.org/Documentation/Cygwin no longer work. Cygwin Setup hangs trying to download setup.xz.sig. It was my understanding that passing -X parameter to the setup will bypass the signature requirements. Tested on two windows machines with same results. Thank you!

**Comment by dcommander** [comment]
Reproduced, but unfortunately I don't know how to fix it.  Setup just appears to hang up.  The `-X` parameter appears to be broken.  I tried creating a dummy file in the repository called "setup.xz.sig".  Still hangs up.  Tried without `-X`.  Still hangs up.  Tried actually creating a proper setup.xz file, signing it with our GPG signing key, and putting the result in setup.xz.sig.  Still hangs up.

I would suggest filing a bug report with the Cygwin developers, or using an earlier version of setup.exe (if you can find it-- I couldn't.)  Supposedly the .sig files in an official Cygwin repository are signed with the official Cygwin signing key, so the only real solutions for unofficial repositories are using `-X` or providing our own signing key and using the `-K` option along with our key URL.  `-X` is logistically easier.  If I were to provide a proper setup.xz.sig file, then I would have to store the private package signing key for The VirtualGL Project on SourceForge.  Given that the primary reason why I started signing packages was because of SourceForge, I'm not willing to trust them with my private key, and even if I was, storing it on a public server like that would represent a security risk.  So that leaves either using `-X` or creating a new key just for the Cygwin packages.  `-X` is a lot easier, so I would strongly prefer to continue doing that.

**Comment by gregwkeller** [comment]
I hit the same issue.  I just downloaded the 2 files, Setup.ini and the VirtualGL .bz2 file and put them in Downloads/VirtualGL/X86_64

Next start Setup-x86_64 -X -L 
Note the X and L are Capital Letters.

Point the install directory to the VirtualGL dir, but not the x86_64 sub directory.

**Comment by dcommander** [comment]
Yeah, that was the way things used to be done (downloading the package and installing it from a local directory using Cygwin setup.)  I created the online Cygwin repository in an attempt to make things easier on Cygwin users, but I guess the Cygwin developers had other ideas.  Confirmed that this is still a problem with the latest & greatest Cygwin setup.

**Comment by dcommander** [comment]
I created a script that will hopefully work around these problems, since it seems that the issue in Cygwin Setup will never be resolved:

https://gist.github.com/dcommander/85fb97a61e0e6ab995a186e5555ab535

This script requires the wget Cygwin package, and it should be run in a Cygwin Bash shell.  It synchronizes the relevant VirtualGL Cygwin repository to a local directory ($HOME/.vglrepo), downloads Cygwin Setup, and launches Cygwin Setup with the appropriate command-line options for installing VirtualGL out of the local repository diectory.

Please let me know if there are any issues with this.  Once it has received a sufficient amount of testing, I'll update the procedure on VirtualGL.org.

**Comment by Vermibus** [comment]
I think the problem is with setup-ini file  (x86_64/x86). 

If you will remove the prefix x86_64/x86 from every install tag in setup.ini files all should be good. 

> install: x86_64/VirtualGL-2.3.3-20131014.tar.bz2 656172 b6034b78c00cd01784a110d872a2ba3c
> ->>
> install: VirtualGL-2.3.3-20131014.tar.bz2 656172 b6034b78c00cd01784a110d872a2ba3c

ofc. In that way you will have to update the links on your webpage to point to the architecture folder: 
eg.:
http://sourceforge.net/projects/virtualgl/files/cygwin  -> files/cygwin/x86_64 || files/cygwin/x86 

If you will provide the link: 
http://sourceforge.net/projects/virtualgl/files/cygwin/x86_64  to the download repo in Cygwin setup he will solve all install links to: 
http://sourceforge.net/projects/virtualgl/files/cygwin/x86_64/x86_64/*  because of that 'x86_64' prefix in setup.ini

**Comment by dcommander** [comment]
I will try that as a workaround, but please note that our Cygwin repository is structured identically to the official Cygwin repositories (for example: http://mirrors.kernel.org/sourceware/cygwin/).

**Comment by dcommander** [comment]
Nope.  Same failure.

**Comment by dcommander** [comment]
@Vermibus, @gregwkeller, @vsantalov, given that there is no apparent workaround other than the script I posted above, I would appreciate it if one or more of you would try out that script and let me know if it works.  If so, then I will make that the official procedure for installing VirtualGL under Cygwin, since it seems that Cygwin Setup will never be fixed.

**Comment by gregwkeller** [comment]
Thanks for your efforts on this.  I re-engineered the solution in the
meantime... Eliminating Windows helps a lot, but the students are revolting
so I may be getting creative in a couple weeks.

Cheers!
Greg

**Comment by martin-fzd** [comment]
[This](https://github.com/VirtualGL/virtualgl/issues/20#issuecomment-283849638) answer from dcommander works for me. Don't forget to adapt the bash script's line endings (see [here](https://stackoverflow.com/a/22073891))

**Comment by dcommander** [comment]
Not sure what you mean about line endings.  Cygwin is perfectly capable of using scripts with Unix line endings.

**Comment by dcommander** [comment]
I've moved the script to its own repository under https://github.com/VirtualGL/vglcygsetup (direct link to the raw code is [here](https://raw.githubusercontent.com/VirtualGL/vglcygsetup/master/vglcygsetup).)  Please file any bugs against the script [here](https://github.com/VirtualGL/vglcygsetup/issues).

**Comment by dcommander** [comment]
An official Cygwin package for VirtualGL is now available. Use Cygwin Setup to install it.
