### ISSUE TITLE
GPU card indexing on Ubuntu 22.04

### ISSUE THREAD

**Issue by cmschroeder91** [VirtualGL/virtualgl#251]
I have two PCs where each PC has two video cards: a P400 for the physical console and RTX 5000 for GPU rendering. In both PCs, `nvidia-smi` reports the P400 as card 0 and the RTX 5000 as card 1. On both PCs I invoke `vglrun -d /dev/dri/card1 <application>` and on the RHEL/Oracle Linux PC my application correctly gets the RTX 5000 GPU, but on the Ubuntu 22.04 PC I erroneously get the P400.

If I invoke `vglrun -d /dev/dri/card0 <application>` on the Ubuntu PC, I get the RTX 5000, even though it is really card 1! The Ubuntu PC has the virtualgl 3.1-20230315 package installed.

**Comment by dcommander** [comment]
I have observed that the EGL device numbers correspond to the underlying PCI device order, whereas the DRI device numbers seem to be arbitrary.  On my multi-GPU system, sometimes the DRI device numbers will even change after a reboot.  Try referencing the device with `egl0` instead of `/dev/dri/card0`.
