### ISSUE TITLE
[Question] getFrame waitUntilComplete() mystery

### ISSUE THREAD

**Issue by d3nd3** [VirtualGL/virtualgl#255]
[https://gemini.google.com/share/29c95f310f7d](https://gemini.google.com/share/29c95f310f7d)

I don't understand why it calls `f = frames[index]; f->waitUntilComplete();`, seemingly blocking for a new frame?

This is the only place the complete signal is waited upon, the signal is fired in 2 other places:
* bottom of sendFrame(): else q.spoil((void *)f, __X11Trans_spoilfct);
* bottom of the thread run(): f->signalComplete();

``` c++
FBXFrame *X11Trans::getFrame(Display *dpy, Window win, int width, int height)

{
	FBXFrame *f = NULL;
	if(thread) thread->checkError();
	{
		CriticalSection::SafeLock l(mutex);
		int index = -1;
		for(int i = 0; i < NFRAMES; i++)
			if(!frames[i] || (frames[i] && frames[i]->isComplete()))
				index = i;
		if(index < 0) THROW("No free buffers in pool");
		if(!frames[index])
			frames[index] = new FBXFrame(dpy, win);
		f = frames[index]; f->waitUntilComplete();
	}
	rrframeheader hdr;
	memset(&hdr, 0, sizeof(hdr));
	hdr.x = hdr.y = 0;
	hdr.width = hdr.framew = width;
	hdr.height = hdr.frameh = height;
	f->init(hdr);
	return f;
}
void VirtualWin::sendX11(GLint drawBuf, bool spoilLast, bool sync,
	bool doStereo, int stereoMode)
{
	int width = oglDraw->getWidth(), height = oglDraw->getHeight();
	FBXFrame *f;
	if(!x11trans) x11trans = new X11Trans();
	if(spoilLast && fconfig.spoil && !x11trans->isReady()) return;
	if(!fconfig.spoil) x11trans->synchronize();
	ERRIFNOT(f = x11trans->getFrame(dpy, x11Draw, width, height));
	f->flags |= FRAME_BOTTOMUP;
	if(doStereo && IS_ANAGLYPHIC(stereoMode))
	{
		stereoFrame.deInit();
		makeAnaglyph(f, drawBuf, stereoMode);
	}
	else
	{
		rFrame.deInit(); gFrame.deInit(); bFrame.deInit();
		if(doStereo && IS_PASSIVE(stereoMode))
			makePassive(f, drawBuf, GL_NONE, stereoMode);
		else
		{
			stereoFrame.deInit();
			GLint readBuf = drawBuf;
			if(stereoMode == RRSTEREO_REYE) readBuf = REYE(drawBuf);
			else if(stereoMode == RRSTEREO_LEYE) readBuf = LEYE(drawBuf);
			readPixels(0, 0, min(width, f->hdr.framew), f->pitch,
				min(height, f->hdr.frameh), GL_NONE, f->pf, f->bits, readBuf, false);
		}
	}
	if(fconfig.logo) f->addLogo();
	x11trans->sendFrame(f, sync);
}
void X11Trans::run(void)
{
	Timer timer, sleepTimer; double err = 0.; bool first = true;
	try
	{
		_vgl_disableFaker();
		while(!deadYet)
		{
			FBXFrame *f; void *ftemp = NULL;
			q.get(&ftemp); f = (FBXFrame *)ftemp; if(deadYet) return;
			if(!f) THROW("Queue has been shut down");
			ready.signal();
			profBlit.startFrame();
			f->redraw();
			profBlit.endFrame(f->hdr.width * f->hdr.height, 0, 1);
			profTotal.endFrame(f->hdr.width * f->hdr.height, 0, 1);
			profTotal.startFrame();
			if(fconfig.flushdelay > 0.)
			{
				long usec = (long)(fconfig.flushdelay * 1000000.);
				if(usec > 0) usleep(usec);
			}
			if(fconfig.fps > 0.)
			{
				double elapsed = timer.elapsed();
				if(first) first = false;
				else
				{
					if(elapsed < 1. / fconfig.fps)
					{
						sleepTimer.start();
						long usec = (long)((1. / fconfig.fps - elapsed - err) * 1000000.);
						if(usec > 0) usleep(usec);
						double sleepTime = sleepTimer.elapsed();
						err = sleepTime - (1. / fconfig.fps - elapsed - err);
						if(err < 0.) err = 0.;
					}
				}
				timer.start();
			}
			f->signalComplete();
		}
	}
	catch(std::exception &e)
	{
		if(thread) thread->setError(e);
		ready.signal();
		_vgl_enableFaker();
		throw;
	}
	_vgl_enableFaker();
}
void X11Trans::sendFrame(FBXFrame *f, bool sync)
{
	if(thread) thread->checkError();
	if(sync)
	{
		profBlit.startFrame();
		f->redraw();
		f->signalComplete();
		profBlit.endFrame(f->hdr.width * f->hdr.height, 0, 1);
		ready.signal();
	}
	else q.spoil((void *)f, __X11Trans_spoilfct);
}
void GenericQ::spoil(void *item, SpoilCallback spoilCallback)
{
	if(deadYet) return;
	if(item == NULL) THROW("NULL argument in GenericQ::spoil()");
	CriticalSection::SafeLock l(mutex);
	if(deadYet) return;
	void *dummy = NULL;
	while(1)
	{
		get(&dummy, true);  if(!dummy) break;
		spoilCallback(dummy)
	}
	add(item);
}
static void __X11Trans_spoilfct(void *f)
{
	if(f) ((FBXFrame *)f)->signalComplete();
}
```

**Comment by d3nd3** [comment]
After thinking about this a bit more deeply, I realize the thead `run()` function will leave the framebuffer in a completed state after drawing with it.

But what about the first framebuffer that gets created , how does anything get added to the queue, I only see `q.add()` called by `11Trans::sendFrame() with q.spoil` , but `sendFrame()` won't be called if `ERRIFNOT(f = x11trans->getFrame(dpy, x11Draw, width, height));` in `VirtualWin::sendX11()` is blocking/waiting for complete signal?

How is anything added to the queue?

**Comment by dcommander** [comment]
What you're seeing is VirtualGL's frame spoiling mechanism.  The two default transports in VirtualGL (the X11 Transport and the VGL Transport) both have a "transport" thread that is separate from the 3D application's rendering thread.  The transports also have a buffer pool, which has a fixed number of "transport buffers" (image buffers in main memory that are used to transfer OpenGL-rendered frames from the VirtualGL Faker to the transport), and a spoiling queue.  (I refer you to the VirtualGL User's Guide for a discussion of the differences between the "spoil first" and "spoil last" algorithms.  For the purposes of this discussion, I will assume the "spoil first" algorithm, because the "spoil last" algorithm is esoteric and infrequently used.)

When the 3D application calls a frame trigger function (e.g. `glXSwapBuffers()`), then the VGL Faker (more specifically `VirtualWin::readback()` and its callees) does the following:

- It requests a new transport buffer from the transport's buffer pool.  Generically speaking, this involves calling the transport class's `getFrame()` method.
- The transport class's `getFrame()` method iterates through the transport buffers in the transport's buffer pool and returns the first one that is "complete."
    - Referring to the `Frame` class (under **common/**) and the `Event` class (under **util/Mutex.cpp**), a transport buffer's "complete" status is implemented via a pthread condition variable.  That means that the condition can only be true in one thread at a time.  Once one thread successfully gets past a call to the transport buffer's `waitUntilComplete()` method, then other threads will block on the transport buffer's `waitUntilComplete()` method until the first thread calls the transport buffer's `signalComplete()` method. All transport buffers are initially "complete" (because no threads have yet called the `waitUntilComplete()` method for any of them), so the transport class's `getFrame()` method will return the first transport buffer in the pool if the transport is being invoked for the first time.
    - We can ignore the transport buffer's "ready" status for the moment.  It is only used with `VGL_SYNC`, a feature that serializes the transport and rendering/readback threads, or when frame spoiling is disabled.  If you disable frame spoiling (via `VGL_SPOIL=0` or `vglrun -sp`), then effectively the rendering/readback frame rate will be locked to the transport frame rate, but the two operations will still occur in parallel.  If you enable `VGL_SYNC`, then the two operations will no longer occur in parallel.  Refer to the code to see how that is implemented.
- Still within the body of `VirtualWin::readback()`, the OpenGL-rendered frame is read back from the GPU-resident Pbuffer (into which VirtualGL has previously redirected the 3D application's OpenGL rendering) into the transport buffer obtained above.
- Still within the body of `VirtualWin::readback()`, the transport buffer is passed to the transport class's `sendFrame()` method.  That invokes `GenericQ::spoil()` with a spoil callback of `__X11Trans_spoilfct()` or `_VGLTrans_spoilfct()`. `GenericQ::spoil()` discards ("spoils") all items currently in the queue and adds the newest transport buffer to the head of the queue.  Effectively, that means that the queue is always 1-deep, so you can think of it as less of a queue and more of a holding slot that also has a semaphore for signaling the transport thread that a new transport buffer is ready.  (If it weren't for the "spoil last" algorithm, we wouldn't actually need to implement a queue at all, but it's convenient to have a single class that both stores the buffer and signals another thread.)
- The transport thread waits until a new transport buffer is available in the queue, then it transports (compresses/encodes/sends in the case of the VGL Transport, or draws in the case of the X11 Transport) the contents of the buffer.  It then calls the buffer's `signalComplete()` method, so the buffer will be available for the VGL Faker to fill again.
    - Because of frame spoiling, the transport thread is not frame-synchronous with the rendering/readback thread.  That's why there are two signaling mechanisms.  The rendering/readback thread waits for a transport buffer to be "complete", fills it, then adds it to the spoiling queue.  The transport buffer waits for a buffer to be available in the queue, transports it, then marks it as "complete".  A buffer is also marked as "complete" if it is spoiled.  (That's what the aforementioned spoil callback functions do.)
    - The X11 Transport has three buffers in its pool because, while it is transporting one buffer, it needs a second buffer available to fill and a third in the queue that can be spoiled if necessary.  The VGL Transport needs a fourth buffer because it performs interframe comparison.
