### ISSUE TITLE
Odd Use Case Question

### ISSUE THREAD

**Issue by aaronjholbrook** [VirtualGL/virtualgl#263]
So, at work use an OpenGL application from Solaris 10 that typically works with X forwarding with SSH to our RHEL8 workstations. Though when we’re in a VNC this is not the case, as the VNC has no access to the GPU, so we want to use VGL to solve this.

The overall situation is that VGL and TurboVNC are installed on my machine and I want the X forwarded application routed through VGL to the actual machine’s GPU and back to the VNC.

If I need to have VGL installed on the Solaris server as well it might be troublesome due to the age of Solaris 10, so if theres a way with VGL only on my RHEL8 machine it is preferable. Any help with this would be greatly appreciated!

**Comment by dcommander** [comment]
VirtualGL doesn't support off-loading rendering to a GPU in another host, and you wouldn't want it to, because the performance and compatibility would be terrible.  (Refer to https://virtualgl.org/About/Background for a discussion of the pitfalls of indirect OpenGL rendering.)  However, VirtualGL 2.5.x was officially supported on Solaris 10, so that code base should work if you build it from source.  VirtualGL 2.6.x may work as well, but that release series was only tested with Solaris 11.

Assuming your VNC server is running on a Linux machine, it is recommended that you use `/opt/VirtualGL/bin/vglconnect` in the VNC session to connect to the Solaris 10 host, then `/opt/VirtualGL/bin/vglrun -c rgb` to run the application on the Solaris 10 host.  That will encode the OpenGL-rendered pixels as uncompressed RGB and send them to the VNC server using the VGL Transport, thus avoiding recompression overhead.  However, this assumes a gigabit or faster network between the VNC server and the Solaris 10 host.

**Comment by dcommander** [comment]
NOTE: I should say that VGL 2.5.x was officially supported on Solaris/x86 10.  The last VGL release series to officially support SPARC was 2.1.x (although 2.2.x may work.)
