### ISSUE TITLE
vglrun wine dx-game.exe, crashes over TurboVNC with amdgpu

### ISSUE THREAD

**Issue by ferrosa** [VirtualGL/virtualgl#27]
Software:
Ubuntu 16.04.1 upgraded from 14.04
VirtualGL 2.5-20160215 (also tried with 2.4)
TurboVNC 2.0.91 (also tried with 1.2.3)
wine 1.8 (also tried with 1.6)
amdgpu 1.1 driver (afaict I'm stuck with this, Radeon R9 380)

The setup is a beefy workstation in the basement and a thin client in the living room. This has worked fine before upgrading Ubuntu on both machines.

`wine game.exe` works locally on the remote machine, games tested are Path of Exile, Age of Wonders 3 and the Windows binary of Europa Universalis 4.
`vglrun glxinfo` and `vglrun glxgears` both give correct results, both locally and via TurboVNC
`vglrun game-bin` works via VNC for games like warzone2100, Factorio  and Heroes of Newerth (all ELF binaries).
`vglrun wine winecfg` via VNC as well as random non-3D mini-app exes work fine.

`vglrun wine game.exe` in VNC crashes with all three games (which work without vglrun locally on the workstation) with the same error:

    Backtrace:
    =>0 0x00000000 (0x0033ef38)
      1 0x7d692d9e in winex11 (+0x32d9d) (0x0033ef58)
      2 0xf6cde5d8 in wined3d (+0x2e5d7) (0x0033efd8)
    [...]

is it useful to upload the 20+MB wine relay log or the 1xxMB full log?
Not sure which (combination) of the software components listed in the beginning is at fault, as I've tried nearly all combinations of the alternative versions in parentheses, and also changing the wine prefix from and to 32bit and installing half of what's available through winetricks (DirectX9 etc.).
Wine works flawlessly without vglrun (specifically dx games) though.

What else should I provide and what's the best way to proceed with debugging?

**Comment by dcommander** [comment]
Can you test the latest code in Git master?  It contains a post-2.5 fix that specifically affects WINE.  Just want to make sure this hasn't already been fixed before I fix it.  :|

**Comment by ferrosa** [comment]
Unfortunately no, rev a143bf3 gives the same errors.

The wine output closest before the failure looks like this, for what it's worth:

    [...]
    fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
    fixme:win:EnumDisplayDevicesW ((null),0,0x321134,0x00000000), stub!
    wine: Unhandled page fault on read access to 0x00000000 at address (nil) (thread 0009), starting debugger...
    [...]


Side note: on Ubuntu (and seemingly also Debian), `libturbojpeg.a` is provided as `/usr/lib/x86_64-linux-gnu/libturbojpeg.a` by the wrong package libjpeg-turbo8, which is accepted by cmake (the compile test in `cmakescripts/FindTurboJPEG.cmake` even passes) but of course doesn't properly build.
To avoid hunting bad symbols and keep the system-required libjpeg-turbo8, simply install libturbojpeg via apt and set `TJPEG_LIBRARY` to `/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0` (not the autodetected `...-gnu/libturbojpeg.a`) in ccmake.
Maybe tighten the `FindTurboJPEG.cmake`? Separate bug report?

**Comment by dcommander** [comment]
I'll look at both issues and determine whether a second bug report is warranted.

**Comment by ferrosa** [comment]
Thanks! I won't be available for testing until Sunday (conference).

**Comment by dcommander** [comment]
Sorry for the delay-- was working 60-70 hours a week throughout August trying to get the TurboVNC 2.1 release out the door.  I was able to bring up a simple D3D 9 example in WINE and VirtualGL under Ubuntu 16.04.  Here are some things for you to sanity check:

* Do you have both the "virtualgl" and "virtualgl32" DEB packages installed?  The latter is needed if you want to run 32-bit Windows 3D applications using VirtualGL and WINE.
* Do OpenGL applications work?  Do the following to find out:
  * Download both **VirtualGL-Utils-2.5.exe** and **VirtualGL-Utils64-2.5.exe** from https://sourceforge.net/projects/virtualgl/files/2.5/
  * `wine VirtualGL-Utils64-2.5.exe`
  * `wine VirtualGL-Utils-2.5.exe`
  * `vglrun ~/.wine/drive_c/Program\ Files/VirtualGL-Utils-2.5-20160215/wglspheres.exe`
  * `vglrun ~/.wine/drive_c/Program\ Files\ \(x86\)/VirtualGL-Utils-2.5-20160215/wglspheres.exe`
* Does a simple Direct3D application work?  Try this one:  http://www.codesampler.com/source/dx9_primitive_types.zip

If all of that works, then the problem must be specific to the games you're trying to run, in which case the only way I'll be able to fix it is to obtain one or more of those games.

**Comment by dcommander** [comment]
RE: libturbojpeg.a, I can't reproduce what you're seeing.  On my machine, with libjpeg-turbo8 and libjpeg-turbo8-dev installed, FindTurboJPEG.cmake locates turbojpeg.h in /usr/include, but the subsequent link test fails because /opt/libjpeg-turbo/lib64/libturbojpeg.a isn't installed.  That's expected behavior, because our build system strongly prefers to use the "official" libjpeg-turbo binaries rather than system-supplied binaries.  Traditionally, this was because the TurboJPEG API wasn't distributed with operating systems that distributed libjpeg-turbo, but now that O/S distributors are starting to include TurboJPEG, FindTurboJPEG.cmake should probably look for a system-supplied version if the official version isn't installed.  However, I don't understand why, in your case, the CMake tests passed but the build subsequently failed.  That's definitely not expected behavior.  Can you provide more details, such as the arguments you're passing to CMake, as well as the CMake output?

RE: performance, I really need the absolute frame rates for local vs. remote before I can tell you why you might be getting a 50-70% slow-down with VGL.  Depending on what the actual frame rates are, that might be expected behavior.  The appropriate way to measure overhead is to run the application on the local display and then run it again (also on the local display) with `vglrun -sp`, comparing the frame rates.  That will eliminate any effects from the VirtualGL image compression/transmission pipeline, although the performance will still be limited by VirtualGL's ability to blit pixels to the screen via X11 (which, on my machine, is limited to about 200 Mpixels/sec.)  At the end of the day, though, remote is never going to be as fast as local.  Even if your measured application performance under VGL were the same as the local performance, there's no way that the compression pipeline or the network could keep up with local performance.  libjpeg-turbo, on modern processors, can compress hundreds of megapixels/sec, and the perceptually lossless compression settings in TurboVNC will allow about 50 megapixels/sec on a 100 Mbit network.  That is definitely fast enough to be "interactive", assuming your desktop size is reasonable, but it'll never be as fast as a PCI Express bus.

**Comment by dcommander** [comment]
1a2b3eb413dc8fe763b29c1059aff04289eff4a3 cleans up TurboJPEG detection somewhat, but it's still not going to work properly with Ubuntu 16.04, because they unfortunately packaged the TurboJPEG libraries incorrectly.  This new commit changes the build system behavior such that, if `TJPEG_LIBRARY` isn't specified, the build system will try to find the TurboJPEG library in the "official" location (/opt/libjpeg-turbo/lib[32|64]) first, and failing that, it will try to link with "turbojpeg".

Under Fedora, this works correctly and causes the build system to use /usr/include as the TurboJPEG include path and /usr/lib[64]/libturbojpeg.so as the TurboJPEG link library, if the official libjpeg-turbo SDK is not installed but the turbojpeg-devel package is.  Under Ubuntu, the build works correctly if the official libjpeg-turbo SDK is installed, but if not, the build system will pick up libturbojpeg.a from the libjpeg-turbo8-dev package, as you pointed out.  The build then fails because that library wasn't built with `-fPIC`.  The workaround is to install the libturbojpeg package and either pass `-DTJPEG_LIBRARY=libturbojpeg.so.0` to the build or `sudo ln -fs libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so` (1a2b3eb413dc8fe763b29c1059aff04289eff4a3 allows the latter to work.  It wouldn't have worked previously.)
