### ISSUE TITLE
Build with Travis and deploy onto Bintray

### ISSUE THREAD

**Issue by frgomes** [VirtualGL/virtualgl#35]
Souceforge with its mirroring makes download inconvenient.
Sometimes downloading from SourceForge simply does work at all.
Bintray: https://bintray.com/

**Comment by dcommander** [comment]
Building with Travis is already happening, and the pre-releases are being deployed to my S3 account:
http://www.virtualgl.org/DeveloperInfo/PreReleases

I have, of late, noticed SF mirror issues as well, and I'm hoping these are just temporary.  I don't seem to have any problems when downloading from within the U.S. (where SF is located), but sometimes my AppVeyor builds for libjpeg-turbo and TurboVNC (which apparently run on nodes located in another country-- probably Canada, because that's where AppVeyor is based) fail because of timeouts when downloading necessary build tools from SF.  Seems to be most prevalent with the pilotfiber mirror, in my experience.

Bintray is not without its problems as well.  I have been experimenting with it to see if it would be a viable replacement for SourceForge FRS, but at the moment, I find Bintray to be somewhat clunky and buggy.  For instance, the inheritance relationship of metadata between packages and repositories in Bintray is unclear, and I can't seem to make their UI properly update the metadata for the test package I created.  I like SourceForge FRS because it allows me to fully control the structure of my file release directory, it allows SSH access, and it doesn't have a lot of unnecessary fluff.  If I need to push new packages for any reason (such as adding or changing digital signatures), it's very easy to push a bunch of new packages for different versions at the same time using a script.  I can easily do this for every package I've ever released since 2004.  I can also SSH directly into the system and manipulate the directory structure using a shell environment.

SF mirrors are supposed to be a feature, but lately, I do agree that a few of them are acting more like bugs than features.  At the same time, however, I am hesitant to make any major moves toward a new FRS, for multiple reasons:
* VirtualGL is a very mature project at this point (we just celebrated our 12th anniversary), and people expect to be able to find our files on SourceForge.  So even if I moved to Bintray or another FRS, there would have to be a transitional period during which the files were made available in both places.  That would be a pain in the butt.
* We are hardly the only project that is using SF for downloads.  Others prominent projects on that site include 7-Zip, MinGW, OpenOffice, FileZilla, VLC.  We cannot as a community just abandon SourceForge wholesale, because a lot of important open source code is still hosted there.  I really think our best move as a community is to report these mirror problems to SF and give them a chance to fix them.
* I am a little paranoid about putting all of my eggs in one basket (https://www.wired.com/2015/06/problem-putting-worlds-code-github/).  GitHub is, at the end of the day, a for-profit U.S. company, just like SourceForge is.  When VirtualGL began as a project, SourceForge was still in its heyday.  Now it has fallen out of fashion, and GitHub is in its heyday, but I'm old enough to remember many instances in which the tables turned overnight.  We all have a vested interest in keeping SourceForge alive as a viable alternative.
* SourceForge is not tied to GitHub in any way, whereas Bintray is.  If, for whatever reason, GitHub ceased to exist, then I would lose the information that has accumulated in our GitHUb trackers since 2015, but the file releases and mailing list archives would be unaffected, and I could move our repository elsewhere and continue doing business.  In other words, I see a tremendous advantage to splitting our project functions across two completely independent web sites.  GitHub seems too much like a single point of failure, particularly given the fact that they don't allow you to download a backup copy of your project's metadata (and yes, I know about BackHub, but that site requires me to enter my credit card number.  No thanks.)
* All of our project's history prior to 2015, including mail archives and bug reports and discussions, etc., is on SourceForge.  This is valuable information that I have to refer to from time to time.  I don't think SF takes over abandoned projects anymore, but still, I am hesitant to abandon the SF project or to give the appearance that it has been abandoned, because, per above, I like the idea that I could move everything back there if I needed to.
* Bintray is based overseas (in Israel), so there are some aspects of U.S. export law that I would have to be cautious of.
* https://github.com/libjpeg-turbo/libjpeg-turbo/issues/45#issuecomment-238137689 summarizes my view of the DevShare controversy.  I am certainly not biased in any way toward SourceForge, but I also think that the open source community has largely misrepresented the facts behind the controversy.  SF is no longer owned by Dice, and even prior to the change of ownership (which occurred earlier this year), they had already taken steps to correct all of the questionable practices that led to the controversy.
* From a legacy point of view, SF has been around longer, and so I trust that they will stay around longer.  I cannot, for instance, use Amazon S3 for deploying releases, because that account is tied to me personally, and if something were to happen to me, that account would go away.  I have similar concerns about Bintray-- it's also tied to me personally, whereas with SourceForge, there are straightforward processes in place that would allow someone else to take over if I was no longer able to maintain those projects.
* SF has unlimited storage, whereas Bintray doesn't.  I think Bintray provides 10 GB for OSS projects, which is enough for all of our existing files, but I still don't like the idea of storage limits.
* http://michaeltunnell.com/blog/15-miscellaneous/53-14-potential-alternatives-to-sourceforge-for-binary-downloads lists basically all of the other problems I have with Bintray vs. SourceForge.  Among them are Bintray's inability to report statistics for each file.

I am definitely not against the idea of using another FRS.  I just don't think the upside of switching to Bintray outweighs the downside-- at least not yet.

**Comment by frgomes** [comment]
Thanks @dcommander for your extensive, detailed and impartial analysis.
Something very rare to be seen these days.
