### ISSUE TITLE
TurboVNC + VirtualGL + steamos-session

### ISSUE THREAD

**Issue by odd-one** [VirtualGL/virtualgl#45]
Hi there!
Lauching vncserver with `-xstartup $DE` option, where `$DE=/usr/bin/custom_script` does not work for steamos-session.
Here's the content of my /usr/bin/custom_script:

`
#!/usr/bin/env bash`
`exec vglrun steamos-session
`

What I get is just a black screen with a total white cursor (actually is the steam cursor, so something is trying to start).
Note that the same script works fine if instead of steamos-session i launch any other session (mate, openbox, etc) as well as any other application and steam itself (but not steam -bigpicture).
Wondering if the problem was related to geometry I try to force a 1366x768 with no luck.

Any help is welcome.

**Comment by dcommander** [comment]
The first problem is that **/usr/bin/steamos-session** is overriding `LD_PRELOAD`:

    export LD_PRELOAD=/usr/lib64/libmodeswitch_inhibitor.so.0.0.0:/usr/lib/libmodeswitch_inhibitor.so.0.0.0

I corrected that by appending `:$LD_PRELOAD` to the end, which effectively appends VirtualGL's fakers to the `LD_PRELOAD` environment variable.  However, then I encountered https://github.com/ValveSoftware/SteamOS/issues/383, which I fixed by ensuring that **/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf** exists.  It then crashes for reasons I cannot fathom:

```
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1489101908)
(process:13523): Pango-CRITICAL **: pango_context_set_font_map: assertion '!font_map || PANGO_IS_FONT_MAP (font_map)' failed
Fontconfig warning: "/home/drc/.local/share/Steam/bin/panorama/etc/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/drc/.local/share/Steam/bin/panorama/etc/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
crash_20170309190303_1.dmp[13577]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170309190303_1.dmp
crash_20170309190303_1.dmp[13577]: Finished uploading minidump (out-of-process): success = yes
crash_20170309190303_1.dmp[13577]: response: CrashID=bp-d4ac1955-978d-4d38-8b45-f3b0b2170309
crash_20170309190303_1.dmp[13577]: file ''/tmp/dumps/crash_20170309190303_1.dmp'', upload yes: ''CrashID=bp-d4ac1955-978d-4d38-8b45-f3b0b2170309''
/home/drc/.local/share/Steam/steam.sh: line 727: 13523 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

Unfortunately I have no further time to look into this.

**Comment by dcommander** [comment]
I spent some more time with this, using the latest & greatest bits from the [Negativo 17 repository](https://negativo17.org/steam/).  It seems as if the proximate cause of the crash is that, somehow, SteamOS is causing the X11 display string associated with the X11 display handle stored by VirtualGL in a particular VirtualWin instance to become invalid.  Thus, checking the display string [here](https://github.com/VirtualGL/virtualgl/blob/master/server/WindowHash.h#L163) triggers the crash.  Unfortunately, valgrind doesn't report any problems, despite the fact that GDB clearly does indicate that ((_XPrivDisplay)vw->getX11Display())->display_name is either NULL or no longer points to a valid memory location.  I cannot fathom how it's possible for that to happen without the application calling `XCloseDisplay()` to close the display handle in question, which it doesn't appear to ever do.  At any rate, I can work around that crash by checking whether `DisplayString(vw->getX11Display())` is non-NULL, but that just kicks the can down the road to expose another crash related to FreeType.  In general, I just don't think it's going to be possible to support Steam and SteamOS at all until/unless Valve makes a concerted effort to make their software more VirtualGL-friendly.  Even if someone were to pay for my labor to really dig into this on a deep level and find a solution, the likelihood that that solution would break in the future is quite high, given how Steam for Linux is architected.  It's already necessary to implement some very unattractive workarounds in order to prevent both Steam and SteamOS from clobbering `LD_PRELOAD`.  VirtualGL has been around for nearly 14 years, and there is no excuse for major Linux OpenGL ISVs not testing their software with it.  I have bent over backwards and spent many sleepless nights making VGL as compatible as I can possibly make it, to make it handle as many "stupid application tricks" as it possibly can, but it would be nice if an ISV met me halfway just once.  Closing as WNF until that situation changes.  It's not that I don't want to support the gaming community.  I do.  It's just that game ISVs don't want to support me, apparently.

**Comment by odd-one** [comment]
Thank you so much for your work man! I really appreciate it.
I wish I could be of any help, but all this stuff is just out of reach to me.
Valve, as many other company out there, seems to have a huge blind corner. For testing purpose I bought a steam link some months ago and I have to say that streaming game with turboVNC with virtualGL works way better on my general purpose HW (using a low end intel stick as a client) than steamlink on their selected HW. this is a huge example of how sometimes big companies are arrogant.

Thanks again, amico.
