### ISSUE TITLE
Vsync / Tearing

### ISSUE THREAD

**Issue by DocMAX** [VirtualGL/virtualgl#50]
I see lots of tearing whatever i do (rgb, jpeg, juv, -sp, -fps).
Is it possible to solve this problem?

**Comment by dcommander** [comment]
Not unless you provide more information about how to reproduce it.  "I see lots of tearing" tells me absolutely nothing.  What are you doing when you see the tearing?  How are you using VirtualGL?  What is your system configuration?

**Comment by DocMAX** [comment]
my setup is:
nvidia gtx970, core i5 -> sending image stream (yuv, ssh) -> intel celeron 3150, intel graphics
both having arch linux
i'm starting with vglrun -c yuv <open gl app>

currently have pcsx2 and dolphin-emu running as opengl applications

i have enabled vsync on the "target" computer (intel celeron) in xorg.conf settings (https://community.linuxmint.com/tutorial/view/2304)

**Comment by dcommander** [comment]
Have you tried

```
export __GL_SYNC_TO_VBLANK=1
```
?

http://us.download.nvidia.com/XFree86/Linux-x86/319.32/README/openglenvvariables.html

**Comment by DocMAX** [comment]
i just did it, but still the same. what else can i do?

**Comment by dcommander** [comment]
I don't know.  You are the only one who has reported this issue, and I am not convinced yet that it is VirtualGL's fault.  Does it occur with other image transports or just with the YUV transport?  I'm not sure why you would be using that transport rather than JPEG.  The YUV transport was originally developed for a very specific type of X proxy (Sun Ray.)  It's not recommended in most cases.

**Comment by DocMAX** [comment]
yuv = 40 fps, jpeg = 15 fps (standard settings, mesaured with +pr switch)

**Comment by dcommander** [comment]
That is extremely slow.  What does the profiling output reveal to be the source of the bottleneck?  Seems to me as if the tearing is a result of slow performance either when the client draws the 3D images or when the server reads them back from the GPU.  My suspicion is the client.  Perhaps it's not fully accelerating X11, and drawing images using XShmPutImage() is causing tearing.  That is definitely not a normal situation.

Things to try:
* Force vglclient to use Pixmaps instead of MIT-SHM.  `export VGL_USEXSHM=0`, then kill all vglclient processes on the client machine and re-connect to the server.
* Force vglclient to use OpenGL.  `export VGLCLIENT_DRAWMODE=ogl`, then kill all vglclient processes on the client machine and re-connect to the server.

NOTE: When trying both of the above, you should use JPEG or RGB.  YUV uses X Video rather than PutImage requests to draw images, so it will be unaffected by those environment variables.

If neither of those things works, then I have no clue.  Sorry.

**Comment by DocMAX** [comment]
tried all combinations. no luck. +pr jumps a lot. readback 70-90 fps, compress 0 50 fps... total 15 fps... jpeg.. so where is the  bottleneck?

**Comment by dcommander** [comment]
Further questions:
* How big is your application window?  70-90 fps is extremely slow for readback, unless you're trying to read a 10-megapixel image.  I seem to remember something I read a few years ago about nVidia artificially limiting the readback performance of their low-end GeForce GPUs in order to encourage people to buy Quadros, so you may be running into that.
* Does the tearing also occur if you run `vglrun /opt/VirtualGL/bin/glxspheres64 -i`?  If not, then it is application-specific.  If so, then it is either a by-product of your system or a by-product of VirtualGL, but since no other users have reported this, my strong suspicion is that it's your system.

You can enable profiling in the client as well by setting `VGL_PROFILE=1` (the output will be in the log stored by the vglconnect script under ~/.vgl.)  I suspect that the overall performance is gated by both your slow server-side readback performance and slow client-side draw performance, but I still suspect that the tearing is coming from the client.  The only thing I can suggest is to try a different client or server machine and see if either one improves the situation.  You might, for instance, try reversing client and server to see if the same thing happens with the nVidia machine as a client, or try using the VGL Transport on the server to connect to the same machine-- i.e. use the server machine as both client and server.

Honestly, the VGL Transport is not a very common use case these days, because of its reliance on remote X11.  The vast majority of VirtualGL users are using some sort of X proxy, such as TurboVNC.  If you're looking for a solution for running VirtualGL with seamless windows, you might try combining VirtualGL with xpra.

**Comment by DocMAX** [comment]
my window is 1920x1080... i will try everything like you described and write back... thank you for your support... do you have any hardware setup where 60fps will work without any problem? what is your personal setup?

**Comment by dcommander** [comment]
I personally use a Quadro K5000 on the server and have several clients (Mac/Intel Iris, Mac/Intel HD 3000, Windows and Linux/AMD APU, Windows and Linux/nVidia Quadro K620), but I have not used the VGL Transport in some time.  I use TurboVNC almost exclusively, as that is the configuration that almost all of my paying customers use.  I do not know answers to your other questions.  I am merely speculating regarding your client-side X server ("2D X server.")  I don't use Arch, nor have I ever run X.org on an Intel adapter.  All I can tell you is that tearing artifacts are generally the result of either:

* single-buffered drawing.  This is why I had you test `VGLCLIENT_DRAWMODE=ogl` and `VGL_USEXSHM=0`, to ensure that the drawing on the client side is double buffered.  This is also why I asked you to test GLXspheres-- because I know that it uses double buffered OpenGL rendering, but perhaps the applications you are testing don't (if so, that would be very unusual.)
* lack of synchronization with the vertical refresh interval.  Generally, though, this would be an issue with local rendering, not with VirtualGL.  Since VirtualGL is using Pbuffers, the vertical sync on the server shouldn't actually affect anything, and now that I think about it, asking you to test `__GL_SYNC_TO_VBLANK=1` was an error on my part.

It's probably just that the Intel VSync settings on the client aren't working properly.

**Comment by DocMAX** [comment]
just wanted to say the tearing is gone. it wasnt virtualgl related but the Xserver. had to prepare my xorg.conf with a vsync option. but still yuv is the fastest codec on every config, also other pc with nvidia card.

**Comment by dcommander** [comment]
It is possible that YUV is faster because of the slow CPU on the client.  The uncompressed options in VirtualGL and TurboVNC were originally implemented during my tenure at Sun Microsystems, because it was discovered that those options were faster when using older (slower) SPARC clients and servers on gigabit Ethernet.  JPEG will definitely be faster on 100-megabit and slower links.

**Comment by DocMAX** [comment]
Maybe the client isn't using hardware acceleration (VAAPI)? How can i check this?

**Comment by dcommander** [comment]
"Hardware acceleration" in the sense of SIMD CPU instructions, yes.  vglclient uses the TurboJPEG API, which is only available with libjpeg-turbo.  libjpeg-turbo will use the SSE2 instructions available in all x86-64 CPUs in order to accelerate JPEG decompression by 2-6x.  When running the 32-bit x86 version of libjpeg-turbo, it will use the best possible SIMD instructions available (MMX or SSE2), but effectively, all modern x86 CPUs have SSE2 instructions.  It has been 15 years since I used an x86 CPU that lacked those instructions (they were introduced with the Pentium 4 in 2001.)
