### ISSUE TITLE
vglconnect with -e = "The server does not appear to have VirtualGL 2.1 or later installed"

### ISSUE THREAD

**Issue by PhilippeRaven** [VirtualGL/virtualgl#53]
Hello !
I'm proudly using VGL since some years now, and it works great.
I never really used vglconnect because vglrun -d was enough for my needs, but today I need to encrypt X11 and VGL.
After re-reading the doc, it seems the only way to encrypt X11 is to use the vglconnect -s argument.
So I tried it, it works. And there's the -e argument, which is VERY interesting, BUT, I can't use it.
Each time I try to "vglconnect -s user@server -e glxgears"  for example, I get the "The server does not appear to have VirtualGL 2.1 or later installed" error, I don't understand why.

I'm using VGL 2.5.2 on both client & server.

Thanks for your help :)
Regards

**Comment by dcommander** [comment]
The `-e` argument has to come before `user@server`, because `-e` is an argument to the vglconnect script whereas `user@server` is an argument to SSH.  Also, you still need to use vglrun, you need to enclose the command passed to `-e` in quotes, and I recommend GLXspheres as a test application rather than GLXgears, so try this:

```
vglconnect -s -e "vglrun -sp /opt/VirtualGL/bin/glxspheres64" user@server
```

You might also want to add `-tt` to the end of the command line.  That forces SSH to allocate a pseudo-terminal, so you will see the output from the application in real time (line buffered as opposed to full buffered.)

**Comment by PhilippeRaven** [comment]
Hello Dcommander,
thanks for this quick reply !
It works like you said, with the `-e` argument before `user@server`.

I tried the `-tt` argument at the end : 
```
 vglconnect -s -e "vglrun -sp /opt/VirtualGL/bin/glxspheres64" user@server -tt

VirtualGL Client 64-bit v2.5.2 (Build 20170302)
vglclient is already running on this X display and accepting unencrypted
   connections on port 4242.

Making preliminary SSH connection to find a free port on the server ...
user@server's password: 
Connection to server closed.
Making final SSH connection ...
:localhost:4242'rding specification '50056
 ```
It stops there.

**Comment by dcommander** [comment]
Works on my version of OpenSSH.  It may be version-specific.  `man ssh`.
