### ISSUE TITLE
Nvidia IFR

### ISSUE THREAD

**Issue by nickblock** [VirtualGL/virtualgl#55]
Hi, 

I'm trying to use virtualgl in conjunction with Nvidia's IFR, for recording to video/stream. I noticed there is a glreadtest that seems to implement it in the utils. Is there any documentation to use that?
I have also tried to use the "shim" example from the NVIDIA capture SDK (the method that preloads a GLX lib to interpose it's own version of GLXCreateWindow, etc). It seems to conflict a little with vglrun, but I can't help but think these things aren't too far apart. Do you have any advice as to what would be the simplest way to use IFR with virtualgl?

Thanks,
Nick

**Comment by dcommander** [comment]
The GLReadTest IFR implementation was primarily an experiment.  I wanted to see whether IFR provided better performance than PBOs (it didn't, unfortunately.)  If we end up implementing H.264/NVENC in VirtualGL, then I'll probably have to use IFR to transfer the encoded stream from GPU memory.  I don't really understand why you need IFR to accomplish frame capture, however, unless you're planning to encode those frames with NVENC.  Otherwise, you'd probably be better served by implementing your own image transport.  You could, for instance, build upon one of the examples (server/testplugin.cpp or server/testplugin2.cpp) to re-implement either the X11 or the VGL Transport with frame capture capabilities.

**Comment by nickblock** [comment]
We are using Unreal and have quite heavy performance requirements as it is. As I understand it the only copy out of the GPU->CPU would be the encoded frame, without it you're going to have at least one more full frame copy won't you? 
Anyway thanks for your advice (and for virtualgl!).

**Comment by dcommander** [comment]
VirtualGL, as it stands now, doesn't use IFR to copy the pixels from GPU to CPU memory.  It uses PBOs.  So if you don't absolutely need to use NVENC, then you might be better off piggybacking off of the existing pixel readback operation so as to avoid two different readback operations.  That's why I suggested developing a custom image transport plugin, but the limitation there is that you would have to encode the video using the CPU (for instance, using libx264 or something like that.)  Otherwise, if you need to use NVENC, then you would probably need to modify the readback code in the VirtualDrawable class in order to encode the frame in the readback/render thread.
