### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by DocMAX** [VirtualGL/virtualgl#58]
I have the following setup:

2 machines with latest arch-linux (Kernel 4.14) and latest VGL (2.6.2). Connected with 1GBit LAN.

Machine 1: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz + GTX 970 + Nvidia Closed Source Driver
Machine 2: Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz + build-in Intel HD Graphics + Kernel Driver

I tried all kinds of switches an i never get over ~20 FPS (testet with glxspheres64).
vglclient with -x and -gl, vglrun with all -c xxx switches (best is YUV so far).
  
I went through the performance guide. Decompression speed is poor here. But my CPU isn't utilizied a lot. Also tried faster machine. No difference.

Total       -   25.89 Mpixels/sec-   12.48 fps-   60.67 Mbits/sec (10.2:1)
Decompress  -   31.06 Mpixels/sec-   14.98 fps
Blit        -  299.95 Mpixels/sec-  144.65 fps

**Comment by dcommander** [comment]
The decompression speed is limiting the overall performance.  When using the VGL Transport, the 3D rendering and pixel readback occur in a different thread than compression and transmission (on the server side), so the maximum frame rate that the server can transmit is usually limited by the server's compression performance.  However, the server cannot transmit frames faster than the client can receive, decompress, and display them.  Your situation is similar to the one described in the User's Guide:
https://cdn.rawgit.com/VirtualGL/virtualgl/master/doc/index.html#hd0017

That decompression performance is suspiciously slow, however, even for a 1.6 GHz Celeron.  By comparison, I can get 100-125 Mpixels/sec on a 2011 Xeon or a 2013 AMD A10-4600M and 50-70 Mpixels/sec on a 2009 Athlon 64.  It makes me suspect that, for whatever reason, your client is not using libjpeg-turbo.  If you're using Arch's build of VirtualGL, then perhaps it wasn't built properly (that has happened before with Arch.)

**Comment by dcommander** [comment]
Scratch that comment about the client not using libjpeg-turbo.  That isn't actually possible, because VirtualGL uses the TurboJPEG API, which isn't available unless you're using libjpeg-turbo.  So it must just really be a slow CPU.  The N3150 supports SSE2 instructions, so I'm not sure why it would be so slow, but you can confirm the raw libjpeg-turbo decompression performance by installing libjpeg-turbo from one of the official packages and running

```
/opt/libjpeg-turbo/bin/tjbench vgl_6434_0018.ppm 95 -subsamp 444 -rgb -quiet
```
(vgl_6434_0018.ppm is available [here](https://libjpeg-turbo.org/pmwiki/uploads/About/3dtestimages.tar.bz2).)

The Arch installation of libjpeg-turbo/TurboJPEG may also have tjbench.  If so, then just use their version of it with the command line above.

**Comment by DocMAX** [comment]
I have the following output. I'm not able to interpret it.

```
All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Image  Image   Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  4:4:4    95    1240   960     37.61   10.46   47.69   

```

**Comment by dcommander** [comment]
Your raw decompression performance is 47.69 Mpixels/sec.  That is definitely slow, but it doesn't seem slow enough to explain the overall slowdown.  What does the VirtualGL profiling information on the server say (`vglrun +pr`)?

**Comment by DocMAX** [comment]
Server looks like this:

```
Compress 0  -  114.82 Mpixels/sec-   55.37 fps
Readback    -  324.02 Mpixels/sec-  156.26 fps
Total       -   26.00 Mpixels/sec-   12.54 fps-   53.27 Mbits/sec (11.7:1)
Compress 0  -  117.32 Mpixels/sec-   56.58 fps
Readback    -  296.95 Mpixels/sec-  143.20 fps
Total       -   27.42 Mpixels/sec-   13.22 fps-   58.85 Mbits/sec (11.2:1)

```

**Comment by dcommander** [comment]
Yeah, definitely a client-side CPU bottleneck, then.  That would explain why YUV is faster.  You may get better performance with TurboVNC, since its encoding methods don't always use JPEG (the "Lossless Tight" encoding method, in particular, is designed for cases in which a gigabit network is available but the client CPU is slow.)

**Comment by DocMAX** [comment]
I switched the client to something faster:

Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz

```
Bitmap     JPEG     JPEG  Image  Image   Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  4:4:4    95    1240   960     111.1   10.46   125.7   
```

But the results are still miserable. Can we dig a bit deeper?

```
Server:
Compress 0  -  103.43 Mpixels/sec-   98.59 fps
Readback    -  321.90 Mpixels/sec-  306.84 fps
Total       -   15.51 Mpixels/sec-   14.78 fps-   47.20 Mbits/sec (7.9:1)

Client:
Decompress  -   46.52 Mpixels/sec-   44.35 fps
Blit        -  459.28 Mpixels/sec-  437.79 fps
Total       -   14.75 Mpixels/sec-   14.06 fps-   45.96 Mbits/sec (7.7:1)
```

**Comment by dcommander** [comment]
I don't know where to dig, since I am unable to reproduce the problem on any of the four machines in my lab.  The slowest machine I have is a 2009 HP Pavilion Slimline s5100z with a dual-core 2.6 GHz AMD Athlon 64 X2 5050e.  It decompresses at ~50-70 Mpixels/sec, which is slower than your i5-2520M, and yet it consistently delivers 34-35 fps with GLXspheres when used as a client for the VGL Transport.

Sanity check:  could it be a network bottleneck?  What type of network are you using?  Does reducing the JPEG quality help?

**Comment by DocMAX** [comment]
I allready tried all JPEG compression levels. Here is my nettest result:

```
Transfer size  1/2 Round-Trip      Throughput      Throughput
(bytes)                (msec)    (MBytes/sec)     (Mbits/sec)
1                    0.121493        0.007850        0.065848
2                    0.114419        0.016670        0.139837
4                    0.118404        0.032218        0.270262
8                    0.114059        0.066890        0.561112
16                   0.113379        0.134583        1.128960
32                   0.118349        0.257860        2.163086
64                   0.200466        0.304467        2.554051
128                  0.201127        0.606930        5.091300
256                  0.200584        1.217148       10.210174
512                  0.202389        2.412592       20.238285
1024                 0.209657        4.657901       39.073305
2048                 0.303529        6.434726       53.978395
4096                 0.326769       11.954174      100.278880
8192                 0.327336       23.866903      200.210093
16384                0.356132       43.874142      368.042981
32768                0.514554       60.732204      509.458656
65536                0.818043       76.401825      640.904958
131072               1.386537       90.152675      756.255449
262144               2.505828       99.767440      836.909947
524288               4.798457      104.200167      874.094352
1048576              9.307596      107.439123      901.264690
2097152             18.317028      109.188022      915.935513
4194304             36.721553      108.927855      913.753073
```

**Comment by dcommander** [comment]
The only thing I can recommend is to try TurboVNC.  That would at least help us zero in on where the bottleneck is.  If TurboVNC is slow as well, then that would point to a system-level performance issue.  I don't get paid for supporting the VirtualGL community, and I have at most 100 hours of funded labor per year to use toward general project maintenance and community support.  Thus, I have only a very limited amount of time to spend helping you diagnose this.

**Comment by DocMAX** [comment]
OK thank you anyway so far. Maybe somebody is reading this someday and helps me.

**Comment by dcommander** [comment]
Well, you could do what I suggested and try TurboVNC to see if it is slow as well.  If so, then that would strongly suggest an issue in your system.

**Comment by DocMAX** [comment]
Isn't TurboVNC doing the same using a Xvnc server? (Compress on server and decompress on Client)

**Comment by dcommander** [comment]
Not exactly the same.  TurboVNC uses a hybrid encoding scheme, so JPEG is only used for high-color areas of the display.  Furthermore, it has a low-CPU-usage mode ("Lossless Tight") that doesn't use JPEG at all and would thus be worth trying with your client/server configuration.

Basically, I need more data points before I can make any intelligent guesses about why you're experiencing this performance problem.  The symptoms are consistent with a slow client machine, but that wouldn't explain why your Core i5 client is also slow.

**Comment by DocMAX** [comment]
OK, i tried the TurboVNC version and had almost the same results. Then i disabled encryption and set JPEG quality to 50 - the results are much better! Is there a way to disable encryption in VGL Transport also?

**Comment by dcommander** [comment]
Are you sure that it was TLS encryption that made the difference?  You initially said that reducing the JPEG quality helped as well.  Can you try each in isolation?  I am beginning to suspect that there is something wrong with your network.  Your NetTest results look normal for a gigabit network, but the behavior you're seeing with VirtualGL and TurboVNC would suggest that your network is somehow bandwidth-constrained.  The actual behavior you're getting is reminiscent of 802.11g.  In a normal TurboVNC environment, TLS encryption shouldn't make more than a 5-10% difference.  But in a normal VirtualGL environment, you should also not be limited to 15 fps over a gigabit link.  Logically speaking, when switching to a faster client didn't make a difference, the next thing to examine would be the network.

Please try the following:
* Reduce the JPEG quality in VirtualGL and see if that improves your frame rate.
* Try disabling TLS encryption and reducing the JPEG quality independently in TurboVNC and see which one improves the frame rate.
* Please provide hard numbers.  "Very good performance boost" can mean many things.  How good?

In TurboVNC, you should always use the profiling feature in the viewer (Ctrl-Alt-Shift-P) to measure frame rate, because the frame rate reported by GLXspheres is not accurate in a VNC environment.  In VirtualGL, you can use the frame rate reported by GLXspheres, as long as you disable frame spoiling (`vglrun -sp`.)

The thing is, on a gigabit network, you should not notice a difference between VGL Transport and TurboVNC performance.  The fact that you are seeing a difference also points to an issue with your network.

The VGL Transport is largely a legacy feature.  It was useful in the early days of the project (2004-2008), because a lot of companies were still using remote X, and the VGL Transport provided a way of easily adding server-side OpenGL rendering to existing remote X environments.  It was also useful for transmitting uncompressed pixels on a server-area network between a dedicated 3D application server and a dedicated X proxy server.  These days, however, few people are using remote X.  All of my paying customers are using TurboVNC or another X proxy with VirtualGL.  So no, there are no plans to back-port the TurboVNC encoding algorithm into VirtualGL.  There would be a licensing conflict, for starters.  VirtualGL's license is based on LGPL, but the TurboVNC encoder is licensed under GPL, and I can't change it, because some of that code was owned by my previous employers.  Hypothetically, someone could write a transport plugin for VirtualGL that used LibVNCServer to do the encoding, but the plugin would have to be licensed under GPL, so it wouldn't be possible to include it in the VirtualGL distribution.

Also note that the VGL Transport does not use encryption unless you tunnel it through SSH (with `vglconnect -s`.)  By default, it is unencrypted.
