### ISSUE TITLE
vglrun dont run glxgears

### ISSUE THREAD

**Issue by hirnfrei** [VirtualGL/virtualgl#59]
Hi!
I try to use virtualgl. On my desktop I install virtualgl, go trough the configuration and try to use vglrun glxgears. But there comes the error:

`libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: couldn't get an RGB, Double-buffered visual`

My desktop use an GeForce GTX 1050ti an runs gentoo linux 64-bit

I cant find the problem :(

**Comment by dcommander** [comment]
The proximate cause of that error is that the `glXChooseVisual()` function returned NULL, indicating that it couldn't find an OpenGL-enabled visual matching the attributes that the application (GLXgears, in this case) requested.  Since VirtualGL has to map X visuals on the 2D X server to GLXFBConfigs on the 3D X server, `glXChooseVisual()` in a VirtualGL environment can return NULL for several reasons:
1. The 2D X server/X proxy has no TrueColor 24-bit visuals (rare.)
2. The 3D X server has no GLXFBConfigs that match the attributes requested in the `glXChooseVisual()` call.
3. The 3D X server has no GLXFBConfigs that support Pbuffer rendering.

Given the "swrast" message, my guess is that you haven't installed the nVidia proprietary drivers, and thus you're using Mesa.  Mesa doesn't always support Pbuffer rendering, and since it isn't fully accelerated, using it with VirtualGL is kind of missing the point anyhow.

You might be able to further diagnose why VirtualGL isn't finding a visual by running GLXgears with `vglrun +v glxgears`.  If you can't figure it out, then post the output of `vglrun +tr glxgears`.

Also, just to be clear, VirtualGL is meant to be installed on an application server.  If it is your intent to access your desktop machine remotely, then that would be the appropriate place to install VirtualGL.  Otherwise, it needs to be installed on the machine that you intent to access remotely.

**Comment by hirnfrei** [comment]
I use the proprietary drivers version 390.12.

vglrun +v glxgears give me the following message

`[VGL] NOTICE: Added /usr/lib64 to LD_LIBRARY_PATH
[VGL] Shared memory segment ID for vglconfig: 190185489
[VGL] VirtualGL v2.5.2 64-bit (Build 20171129)
[VGL] Opening connection to 3D X server :0
[VGL] NOTICE: Replacing dlopen("libGL.so.1") with dlopen("libvglfaker.so")
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[VGL] WARNING: VirtualGL attempted and failed to obtain a true color visual on
[VGL]    the 3D X server :0 suitable for off-screen rendering.
[VGL]    This is normal if the 3D application is probing for visuals with
[VGL]    certain capabilities, but if the app fails to start, then make sure
[VGL]    that the 3D X server is configured for true color and has accelerated
[VGL]    3D drivers installed.
Error: couldn't get an RGB, Double-buffered visual
`

VirtualGL is installed on the machine that I want to access remotely. If I run glxgears all is fine.

**Comment by dcommander** [comment]
What is the output of 
```
/opt/VirtualGL/bin/glxinfo -display :0 -c
```
?

**Comment by hirnfrei** [comment]
`bash: /opt/VirtualGL/bin/glxinfo: Datei oder Verzeichnis nicht gefunden`

There isnt a directory /opt/VirtualGL

**Comment by dcommander** [comment]
OK, apparently you are using someone else's VirtualGL package, then.  I can only support our official VirtualGL packages, because O/S distributors have a bad habit of packaging VirtualGL in ways that break it.  Please try installing our official DEB package (which should be possible on Gentoo) and uninstalling the Gentoo-supplied package.  If that works, then problem solved.  If that doesn't work, then you'll at least be able to show me the output of

```
/opt/VirtualGL/bin/glxinfo -display :0 -c
```
as requested.

**Comment by hirnfrei** [comment]
I build virtualgl from source. No problems.

The result is: [glxinfo](url=https://pastebin.com/wpdRPwzc)

**Comment by dcommander** [comment]
Please clarify what you mean by "No problems."  Is the original issue fixed?  If not, then I have no idea what else to tell you, because the glxinfo output looks perfectly normal.

**Comment by hirnfrei** [comment]
No problems means building virtualgl from source runs without any errors.

Thats tricky that glxinfo looks perfect...

**Comment by dcommander** [comment]
OK, that means that there is something wrong with the Gentoo package.  Glad to know you were able to get it working.

**Comment by hhfeuer** [comment]
Hi there,
same problem here on Gentoo but I identified the cause. It seems related to the glvnd stub libs provided with mesa (mesa-18.1.6 installed):
lrwxrwxrwx 1 root root     14 22. Aug 14:05 /usr/lib/libGL.so -> libGL.so.1.2.0
lrwxrwxrwx 1 root root     14 22. Aug 14:05 /usr/lib/libGL.so.1 -> libGL.so.1.2.0
libGL.so.1.2.0 is the mesa glvnd stub which is used per default in Gentoo but with it VGL always tries to load the swrast driver. Replacing it with the stub from the nvidia driver package, libGL.so.1.7.0
lrwxrwxrwx 1 root root     23 30. Aug 13:03 /usr/lib/libGL.so -> /usr/lib/libGL.so.1.7.0
lrwxrwxrwx 1 root root     23 30. Aug 13:02 /usr/lib/libGL.so.1 -> /usr/lib/libGL.so.1.7.0
makes VGL work.
With everything else, the mesa glvnd stub works with the nvidia driver.
Question is, is this a shortcoming of VGL or a bug in mesa?

**Comment by dcommander** [comment]
That seems like a distribution-specific problem.  On Fedora, for instance, which is also GLVND-enabled, libGL.so and libGL.so.1 symlink to libGL.so.1.7.0, and there is no libGL.so.1.2.0.  libGL.so.1.7.0 is provided by the package "libglvnd-glx" on Fedora.  Not sure about Gentoo, as I've never used it.

**Comment by hhfeuer** [comment]
Yes, of course this is distribution specific. Some distibutions (like Gentoo) use the stub from mesa (1.2.0) others (like Fedora, obviously) the one from Nvidia (1.7.0). VGL should be working with both, otherwise VGL would be distibution specific as well. It's just the question whether this has to be fixed in VGL or in mesa.

**Comment by hhfeuer** [comment]
I looked a bit deeper into Gentoo's opengl stuff and had to find out that glvnd on Gentoo is still wip, so this explains why installing the Nvidia stubs fixes the VGL situation. Still a riddle though why VGL ignores the current Gentoo opengl system. Maybe I'll take a look at VGL, otherwise it'll be fixed over time when Gentoo correctly implements glvnd. Meanwhile, people have this thread for a workaround.

**Comment by dcommander** [comment]
VGL accesses GLX/OpenGL functions in two ways:
- (Most common) through whichever OpenGL library the 3D application is linked against (using the special `RTLD_NEXT` option to `dlopen()`.)  This is usually libGL.so.1, but it depends on how the 3D application was linked.  VirtualGL has no control over that.
- (Least common) If an application uses `dlopen()`/`dlsym()` to access GLX/OpenGL functions, then VirtualGL will intercept the `dlopen()` call and modify it such that the application opens libvglfaker.so instead.  VGL still uses `dlopen(RTLD_NEXT, ...)` by default to obtain the real GLX/OpenGL symbols, but in this case, `RTLD_NEXT` is relative to libvglfaker.so, so it will be libGL.so.1 by default (since that's what libvglfaker.so is linked against.)

Long and the short of it: unless libGL.so.1 is GLVND-aware, then VirtualGL will only be able to load whichever OpenGL implementation is symlinked to libGL.so.1.  If you want to load another OpenGL implementation, then you can try setting the `VGL_GLLIB` environment variable.  This will change the default behavior and cause VirtualGL to look for GLX/OpenGL symbols in a specific library, rather than using `RTLD_NEXT`.

It is conceivable that VGL could be made GLVND-aware as well, but care would have to be taken in order to ensure that backward compatibility is maintained with non-GLVND-aware systems.  I anticipate that it would be a non-trivial project.

**Comment by xlla** [comment]
failure on raspberry pi 4 64bit
<pre>
rpi4:~$ DISPLAY=:1 vglrun -v -tr glxgears -info
failed to create drawable
[VGL] ERROR: in OGLDrawable--
[VGL]    83: Could not create Pbuffer
rpi4:~$ DISPLAY=:1 vglrun -v +tr glxgears -info
[VGL 0xaca8e450] XOpenDisplay (name=NULL dpy=0x5575657f40(:1) ) 1.931906 ms
[VGL 0xaca8e450] glXChooseVisual (dpy=0x5575657f40(:1) screen=0 attrib_list=[0x0004 0x0005 0x0008=0x0001 0x0009=0x0001 0x000a=0x0001 0x000c=0x0001 ] glxattribs=[0x000c=0x0001 0x0005=0x0001 0x0008=0x0001 0x0009=0x0001 0x000a=0x0001 0x8011=0x0001 0x8010=0x0006 ] [VGL] dlopen (filename=libGL.so.1 flag=258 retval=0x7fad473520)
[VGL] dlopen (filename=/usr/lib/dri/tls/swrast_dri.so flag=258 retval=0x00000000)
[VGL] dlopen (filename=/usr/lib/dri/swrast_dri.so flag=258 retval=0x55756a5240)
vis=0x5575676a70(0x21) config=0x55756c5980(0x7a) ) 65.917015 ms
[VGL 0xaca8e450] XCreateWindow (dpy=0x5575657f40(:1) parent=0x0000006a x=0 y=0 width=300 height=300 depth=24 c_class=1 visual=0x55756598c0(0x21) win=0x00c00002 ) 0.019073 ms
[VGL 0xaca8e450] glXCreateContext (dpy=0x5575657f40(:1) vis=0x5575676a70(0x21) share_list=0x00000000 direct=1 config=0x55756c5980(0x7a) ctx=0x5575676f70 ) 212.454081 ms
[VGL 0xaca8e450] glXMakeCurrent (dpy=0x5575657f40(:1) drawable=0x00c00002 ctx=0x5575676f70 
[VGL 0xaca8e450]   XQueryExtension (dpy=0x5575657f40(:1) name=XVideo *major_opcode=150 *first_event=94 *first_error=153 ) 0.179052 ms
[VGL 0xaca8e450] 
[VGL 0xaca8e450]   XQueryExtension (dpy=0x5575657f40(:1) name=XVideo *major_opcode=150 *first_event=94 *first_error=153 ) 0.213861 ms
[VGL 0xaca8e450] 
[VGL 0xaca8e450]   XQueryExtension (dpy=0x5575657f40(:1) name=Generic Event Extension *major_opcode=128 *first_event=0 *first_error=0 ) 0.181913 ms
[VGL 0xaca8e450] failed to create drawable
[VGL] ERROR: in OGLDrawable--
[VGL]    83: Could not create Pbuffer
</pre>

**Comment by dcommander** [comment]
@xlla That is completely unrelated to this issue.  Please stay on-topic.  Furthermore, Raspberry Pi is not supported as 
a VirtualGL server platform.  If the community wants to provide support for that platform, then great.  The community needs to figure out how to make VirtualGL work properly with it, assuming that such is possible.  Refer to: https://virtualgl.org/Documentation/OSSupport.

**Comment by xlla** [comment]
@dcommander all right!  I am finally got it.
<pre>
rpi4:~$ vglrun -c proxy -v -tr glxgears -info
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    10.0.0.106, the IP address of your SSH client.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
GL_RENDERER   = V3D 4.2
GL_VERSION    = 2.1 Mesa 20.3.0-rc1
GL_VENDOR     = Broadcom
...
134 frames in 5.0 seconds = 26.752 FPS
134 frames in 5.0 seconds = 26.755 FPS
</pre>

**Comment by dcommander** [comment]
@xila Glad to hear it, but in the future, please:

* Do not hijack GitHub issues with unrelated topics.  Post a new issue.
* If you report an issue with VirtualGL and resolve that issue on your own, please post the solution so that others who stumble upon the thread via Google might benefit from your solution.
* Do not tag me unless you need my immediate attention.

This is my place of business, so I appreciate your cooperation in keeping it as productive as possible.  Thanks.
