### ISSUE TITLE
glxgears  doesn't show gears (only a black window)

### ISSUE THREAD

**Issue by ohcfe** [VirtualGL/virtualgl#62]
I'm trying to connect to a linux host (CentOS7) from a windows 10 laptop and forward GL accelerated programs. Running glxgears as a testcase I get only a black window with no FPS reports.

    mgesing@L-HAM-A129060 ~
    $ vglconnect rice
    
    VirtualGL Client 64-bit v2.5.2 (Build 20170302)
    vglclient is already running on this X display and accepting unencrypted
       connections on port 4242.
    
    Last login: Thu Feb 22 15:38:00 2018 from 132.156.103.56
    [mgesing@rice ~]$ vglrun glxgears
    [VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
    [VGL]    132.156.103.56, the IP address of your SSH client.

I realize this isn't a lot of information to go on, is there some kind of verbose mode for vglrun or vglconnect, or logfile to look at?

Thanks.

**Comment by dcommander** [comment]
Yes, `vglrun +v` will give verbose output, and `vglrun +tr` will give tracing output (which shows, in real time, which GLX/OpenGL calls are being intercepted.)  However, given that there were no error messages on the server, I would suspect a client-side issue, so check under ~/.vgl on the client machine for the vglconnect log, and see if there are any errors in it.

**Comment by dcommander** [comment]
Issue assumed resolved due to lack of response from the user.  If you are still encountering problems, then follow up.

**Comment by 8greg8** [comment]
Dear @ohcfe. Can you please describe how you solved your problem? I have the same problem (Ubuntu 16.04) and cannot find the solution.

**Comment by ohcfe** [comment]
I didn't solve it, I just got too busy at work to continue debugging it.

My work-around is to use ssh X forwarding instead of virtualGL

I completely understand @dcommander closing the issue, as I was completely unresponsive.

Sorry I couldn't be of more help.

**Comment by dcommander** [comment]
I can almost guarantee you that the problem is related somehow to the VirtualGL Client.  You can probably work around it by running VirtualGL in a TurboVNC session instead.  That is how most people use VirtualGL these days.

**Comment by ohcfe** [comment]
VirtualGL is now working for me!

The only change I made was to move two GPUs from the master node of my cluster (the one I'm  using vglrun on) to a compute node. Now that the master node has only one GPU vglconnect  and vglrun work as intended.

I'm assuming that my original problem was caused by some sort of mis-configuration of my multi-GPU setup.

All the best.

**Comment by surak** [comment]
> I can almost guarantee you that the problem is related somehow to the VirtualGL Client. You can probably work around it by running VirtualGL in a TurboVNC session instead. That is how most people use VirtualGL these days.

I would like to run it without turboVNC, tbh. On the standard Mac 10.14.6 client, the same happens. 

vglrun +v shows:

```
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]  XXXXXXX, the IP address of your SSH client.
[VGL] Shared memory segment ID for vglconfig: 6979629
[VGL] VirtualGL v2.6.1 64-bit (Build 20190101)
[VGL] Opening connection to 3D X server :0
[VGL] Using Pbuffers for rendering
```

**Comment by ArmandB** [comment]
I had this issue as well when trying "8.1 VGL Transport with X11 Forwarding. "

I played around with it and noticed that even if the vglclient wasn't running on the client that I'd get the black screen. When I would use vglrun -c proxy it would work but the performance was low.

I ended up using the "7.3 VGL Transport with X11 Forwarding and SSh Tunneling", and that worked better for me. Gave me 10x the frame rate of the -c proxy. Remote server was Ubuntu 18.04.5 LTS and client was Ubuntu 16.04.

**Comment by dcommander** [comment]
> I played around with it and noticed that even if the vglclient wasn't running on the client that I'd get the black screen. When I would use vglrun -c proxy it would work but the performance was low.

Did you mean "even if the vglclient **was** running"?  Given that it worked with SSH tunneling, I suspect that your client's firewall was blocking inbound traffic to vglclient, which would explain the black screen.  You should be able to confirm in the vglconnect log on the client machine that no inbound connections are occurring.  You have to open up Port 4242 on the client in order to use the VGL Transport + VirtualGL Client without SSH tunneling.  But there is very little performance penalty for using SSH tunneling on modern systems (the 20-40% claim in the User's Guide needs to be updated), so if you're happy with `vglconnect -s` (VGL Transport with X11 forwarding and SSH tunneling), there's nothing wrong with that solution.  Bear in mind that the VGL Transport is a nearly 20-year-old idea that was introduced in the days when Remote X was the most popular (and, in some cases, the only viable) remote display solution for Un*x applications.  Back then, firewalls weren't very common on desktop machines, SSH tunneling had a more serious performance penalty, and X servers typically had open TCP ports.  These days, SSH tunneling probably makes more sense.  The only major disadvantage of SSH tunneling is that it requires making two connections to the VirtualGL Server (once to obtain a free port on the server and once to establish the SSH tunnel), which would require you to enter your password twice if you aren't using public key authentication.

**Comment by ArmandB** [comment]
> > I played around with it and noticed that even if the vglclient wasn't running on the client that I'd get the black screen. When I would use vglrun -c proxy it would work but the performance was low.
> 
> Did you mean "even if the vglclient **was** running"?

Yes. Both when the vglclient **was** running and **was not** running, I'd get the black screen. I thought I'd mention it b/c it's in line with what you had said about the issue being with the client. I had checked the vglconnect log on the client and the file was empty, which also makes sense b/c I guess it wouldn't have been if there was a connection. I am happy with the vglconnect -s solution!

I actually wasn't expecting a response xD I had just commented just in case it would help someone in the future. Thank you for the response, and for teaching me something about SSH tunneling and VGL Transport:)
