### ISSUE TITLE
ERROR: Could not open display

### ISSUE THREAD

**Issue by DimaZhu** [VirtualGL/virtualgl#63]
Hi, i'm trying to use vgl, but can't handle it. Hope you can help me. 
I went step by step on this [documentation](https://cdn.rawgit.com/VirtualGL/virtualgl/2.5.2/doc/index.html) , but when i configured vgl server i chose options without vglusers (not recommended), because file /etc/opt/VirtualGL/vgl_xauth_key wasn't generated otherwise. So, when i tried to vglrun glxgears i've got:
 `[VGL] ERROR: Could not open display 192.168.0.126:0.`
But i tried to ssh -X glxgears and everything worked as expected.

**Comment by dcommander** [comment]
`ssh -X glxgears` worked because that causes the OpenGL commands to be transmitted through the SSH tunnel and rendered on the client machine.  That type of rendering (indirect OpenGL) is, specifically, what VirtualGL is designed to circumvent.

Please tell me the following:
* The operating system you are running on the server (distribution name and version)
* The display manager (example: GDM) that you are running on the server
* The values of the `DISPLAY` and `VGL_DISPLAY` environment variables (in the SSH session on the server)
* Which machine 192.168.0.126 is (client or server)

**Comment by DimaZhu** [comment]
1. OS is Ubuntu 16.04.1
2. Display manager is lightdm
3.  `DISPLAY`  is 192.168.0.126:0, `VGL_DISPLAY` is empty
4. 192.168.0.126 is client ip.

**Comment by DimaZhu** [comment]
Same thing on Mageia Linux. Obviously i'm doing something wrong, but i can't figure out what

**Comment by dcommander** [comment]
The `DISPLAY` variable is suspicious.  Normally `DISPLAY` should be set to `localhost:n.0` (where `n` is a display number chosen by the SSH server) when using SSH X11 tunneling.  When using the VGL Transport, SSH X11 tunneling is normally necessary with modern operating systems, because most of them do not allow TCP connections to the X server by default.  I would really recommend that you use TurboVNC instead of the VGL Transport, since TurboVNC creates a virtual X display on the server and thus eliminates the need to deal with the client-side X display at all.  However, if you need to use the VGL Transport, then be sure to use the vglconnect script to connect to the server, since vglconnect enables SSH X11 tunneling by default.  If that still isn't working, then check your server's configuration.  There is no way that the `DISPLAY` environment variable would be set to `{client IP}:0` by default.  Something on the server is setting that environment variable that way.  I imagine that simple X11 applications, such as `xdpyinfo`, also do not work in your environment, so there is no way that the VGL Transport can work until that is fixed (the VGL Transport uses an image-based thin client protocol for sending the OpenGL-rendered pixels to the client, but it uses remote X11 for everything else.)
