### ISSUE TITLE
Not creating vgl_xauth_key when using gdm3 in ubuntu server

### ISSUE THREAD

**Issue by 8greg8** [VirtualGL/virtualgl#65]
Dear all.

I found out vgl_xauth_key is not created when I use gdm3. I think this is a bug.

My configuration:
Ubuntu LTS 16.04 server
VirtualGL 2.5.2
installed gdm3 and lightdm

Proof:
```
sudo rm /etc/opt/VirtualGL/vgl_xauth_key
rm ~/.Xauthority
sudo systemctl stop gdm
sudo systemctl stop lightdm
sudo dpkg-reconfigure gdm
```

Choose gdm3 as default display manager

`sudo /opt/VirtualGL/bin/vglserver_config`

All options Y [yes]

```
sudo systemctl start gdm
ls /etc/opt/VirtualGL
```

There is no vgl_xauth_key. Then we check
`/opt/VirtualGL/bin/vglgenkey >vglgenkey.out 2>&1'

and get

```
xauth:  timeout in locking authority file /etc/opt/VirtualGL/vgl_xauth_key
xauth:  file /home/user/.Xauthority does not exist
xauth:  timeout in locking authority file /etc/opt/VirtualGL/vgl_xauth_key
chmod: cannot access '/etc/opt/VirtualGL/vgl_xauth_key': No such file or directory
```

If lightdm is used as default vgl_xauth_key is generated.

**Comment by dcommander** [comment]
Known bug in GDM.  Not sure why it remains unfixed upstream.
https://bugzilla.redhat.com/show_bug.cgi?id=851769

**Comment by dcommander** [comment]
NOTE: Ubuntu is aware of this:

https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1774081

as are the GNOME developers:

https://gitlab.gnome.org/GNOME/gdm/issues/317

The issue currently affects the default install of Ubuntu 18.04 LTS, since it ships with GDM 3 rather than LightDM, as well as Fedora.  The only way to work around it is to install and activate LightDM as the default display manager.  On Ubuntu 18. this can be done as follows:

```
sudo systemctl disable gdm3
sudo apt install lightdm
sudo systemctl enable lightdm
```

Run or re-run vglserver_config after performing the steps above.

**Comment by drigz** [comment]
For anyone looking for the latest on this issue, it appears that versions >=2.6.2 no longer recommend lightdm, and instead say:

> On Wayland-enabled Linux machines running GDM, configuring the machine as a VirtualGL server will disable the ability to log in locally with a Wayland session. In general, logging in locally once the machine has been configured as a VirtualGL server is discouraged, as this could disrupt VirtualGL’s connection to the 3D X server and thus cause OpenGL applications running with VirtualGL to abort or freeze.

https://github.com/VirtualGL/virtualgl/commit/aa5ff87b9a7a569a62ffe3825265b447b863b57f

**Comment by dcommander** [comment]
@drigz Referring to the GitLab issue above, it became apparent that the GNOME developers had no intention of fixing the issue, even if the display manager was using X11 rather than Wayland, so I worked around it by using a greeter autostart script.  Users can still use LightDM if they prefer, but such is no longer necessary.

**Comment by biochem-fan** [comment]
> I worked around it by using a greeter autostart script. Users can still use LightDM if they prefer, but such is no longer necessary.

Unfortunately this is not true with my Ubuntu 20.04 LTS.

`/etc/opt/VirtualGL/vgl_xauth_key` is created with LightDM, but not with gdm3.

**Comment by biochem-fan** [comment]
Never mind; the above was a false alarm.

I had to add the `gdm` user to the `vglusers` group. Otherwise gdm3 fails to launch X and thus `xauth` does not work.

Just for record, adding `--disable-acceleration-check` to `gnome-session` didn't help, because `gnome-shell` died saying "Unable to initialize the Clutter backend".

**Comment by biochem-fan** [comment]
@dcommander Yes, that was what happened.

**Comment by dcommander** [comment]
OK, I'll add a note to the User's Guide.
