### ISSUE TITLE
VirtualGL with KVM PCI passthrough nvidia and vnc

### ISSUE THREAD

**Issue by waltervargas** [VirtualGL/virtualgl#67]
Hi, 

Host: Dell Precision 5510 with Dual Card Nvidia + Intel
Guest: Archlinux with the Nvidia card available via PCI passthrough.
           + VirtualGL
           + TigerVNC

Is possible to use the GPU of my Nvidia card for a VirtualGL setup inside the Guest in combination with tigervnc server?

**Comment by dcommander** [comment]
It should be, yes.  VirtualGL doesn't really care about the driver-level details of the GPU.  It just needs to have an X server set up on that GPU (we call that the "3D X server") so that it can create Pbuffers via the GLX API (Note that the X server can be headless.)  With PCI pass-through, the guest should behave just like a host from VirtualGL's point of view.

**Comment by waltervargas** [comment]
but the X server is not able to use the nvidia card, this is that kind of cards "hybrid graphics".
