### ISSUE TITLE
GNOME unusable with virtualgl

### ISSUE THREAD

**Issue by redg3ar** [VirtualGL/virtualgl#68]
The effect is visible here:
https://gfycat.com/ReliableSevereAsiansmallclawedotter
This happens on both vnc and locally.
Thank you for your amazing work on virtualgl, it is a wonderful application.

**Comment by dcommander** [comment]
Try setting `VGL_WM=1` in the environment or launching the window manager with `vglrun +wm`.  GNOME 3 is known to work with TurboVNC 2.1.x, when using 3D window manager mode (when you launch **/opt/TurboVNC/bin/vncserver** with `-3dwm`, it automatically tweaks a few things in the **~/.vnc/xstartup.turbovnc** file and runs the WM with `vglrun +wm`.)  With TurboVNC 2.2.x (which is soon to be in beta), GNOME 3 is known to work with the built-in (unaccelerated) OpenGL implementation as well.  Refer to:

[TurboVNC 2.1.x Window Manager Compatibility Report](https://turbovnc.org/Documentation/Compatibility)
and
[TurboVNC 2.2.x Window Manager Compatibility Report](https://turbovnc.org/Documentation/Compatibility22)

There are, however, some [known issues](https://github.com/TurboVNC/turbovnc/issues?utf8=%E2%9C%93&q=label%3A%22GNOME%203%22).

These are a consequence of running GNOME 3 in a user-space (non-systemd) X proxy environment and aren't specific to VirtualGL.  Unfortunately, only a couple of them have workarounds.  In general, MATE is a much better option for a VNC environment.  Even with a working GNOME 3/VGL configuration, it still isn't going to be very fast, because the compiz compositing window manager that underlies it relies upon the texture-from-pixmap extension in OpenGL.  VirtualGL is a split rendering solution, so it redirects all OpenGL rendering onto a different X server (the "3D X server") than the one that the application is actually displaying to (the "2D X server.")  That allows the OpenGL rendering to be hardware-accelerated even if the 2D X server lacks hardware acceleration.  However, split rendering is problematic for certain OpenGL features, and texture-from-pixmap happens to be one.  VirtualGL has to distinguish between an X Pixmap and a GLXPixmap, the former of which is stored on the 2D X server and the latter of which is stored on the 3D X server.  However, a normal X/GLX environment does not distinguish between the two.  That means that, within the body of `glXBindTexImageEXT()`, VirtualGL has to copy the contents of the Pixmap from the 2D X server to the 3D X server (using `XGetImage()`.)  Then, when the application (compiz) calls `XCopyArea()` to transfer the pixels from the GLXPixmap to the Window, VirtualGL has to use `glCopyPixels()` to copy the contents of the Pixmap from the 3D X server back to the 2D X server.  There are likely some optimizations that could be made to VirtualGL's texture-from-pixmap implementation, but that feature was a funded development opportunity, and no one has thus far stepped forward to fund performance improvements to it (most commercial VirtualGL/TurboVNC installations are using MATE or another 2D window manager, so it's hard for anyone to make a business case for improving GNOME 3 performance in VGL-- particularly not when there are so many known issues with it in a remote display environment.)

**Comment by redg3ar** [comment]
the problems continue both with running with +wm, and running xstartup.turbovnc
Even without using turbovnc, virtualgl still has problems with gnome
Compiling from source gives me some newer errors: 
```
$ TVNC_3DWM=1 TVNC_WM="gnome-session --debug" .vnc/xstartup.turbovnc 
/etc/X11/xinit/xinitrc: line 51: twm: command not found
/etc/X11/xinit/xinitrc: line 52: xclock: command not found
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by dcommander** [comment]
That's because the VGL fakers probably need to be under **/usr/lib\*** in order to run the window manager in VirtualGL.  There is no need to compile from source.  Literally the latest VirtualGL code is available in binary form here:
https://sourceforge.net/projects/virtualgl/files/2.5.90%20%282.6beta1%29/

You haven't mentioned which O/S you're running, which is a critical detail.  It seems that there may be some issue with your **/etc/X11/xinit/xinitrc** file.

**Comment by redg3ar** [comment]
The log above is pretty misleading and unrelated to this issue, I apologize. I am running arch linux, I compiled from source because it was easy to do on my os, but it does the same when switch back to binary. There is `libvglfaker.so libvglfaker-nodl.so libdlfaker.so libgefaker.so` in /usr/lib.  I tried vglrun with many different options and environment variables.
Heres a quick summary of the problems that happen:
 
vglrun +wm gnome-desktop fails, the flag "--debug" tells me that 
```
** (process:4142): WARNING **: hardware acceleration check failed: Child process exited with code 1
** (process:4142): WARNING **: software acceleration check failed: Child process exited with code 1
``` 
running gnome-session with --disable-acceleration-check causes it to start, but with symptoms like the video I sent above

These things happen in both vglrun on the same machine providing the acceleration and when using turbovnc.

Sorry about the misunderstanding. Any other logs you need?

**Comment by dcommander** [comment]
Why did I suspect you were going to say Arch Linux?  No offense, but when people report problems like this that I can't reproduce, about 9 times out of 10 it's because they're running Arch Linux.  In the past, the Arch distributors were shipping a completely borked build of VirtualGL.  Since you've tried building from source, that apparently isn't the problem you're encountering, but more generally, Arch is a bleeding-edge distro that presents something of a moving target, so even if I spent a lot of unpaid hours making this work on your system, it could break next week due to no fault of mine.  I simply don't and can't support Arch.  If you can reproduce this on Fedora or CentOS or SLES or Debian or Ubuntu, I can help you, but also understand that there is no funding to look into this, so even if the problem is reproducible on one of those distros, it might be a few months before I could free up the time to diagnose it.  Once again, MATE is the recommended window manager for TurboVNC.

**Comment by redg3ar** [comment]
Thank you for the help, Ill get back to you if it affects me on another os
