### ISSUE TITLE
VirtualGL doesn't work, glxinfo segfault.

### ISSUE THREAD

**Issue by Danct12** [VirtualGL/virtualgl#74]
I've setup VirtualGL on my host, but when I try to connect VirtualGL on a different machine, it doesn't work. It connects fine without any errors, but when I try to run `vglrun glxgears`, it doesn't work, no moving gears or anything, nothing.

Below is the me running it with verbose mode.
```
danct12@debian:~$ vglrun +v glxgears
[VGL] Shared memory segment ID for vglconfig: 6389773
[VGL] VirtualGL v2.5.2 64-bit (Build 20170302)
[VGL] Opening connection to 3D X server :0
[VGL] NOTICE: Replacing dlopen("libGL.so.1") with dlopen("libvglfaker.so")
Error: couldn't get an RGB, Double-buffered visual
danct12@debian:~$ 
```

Below is GLXInfo.
```
danct12@debian:~$ vglrun +v glxinfo
[VGL] Shared memory segment ID for vglconfig: 6422541
[VGL] VirtualGL v2.5.2 64-bit (Build 20170302)
name of display: localhost:12.0
[VGL] Opening connection to 3D X server :0
[VGL] NOTICE: Replacing dlopen("libGL.so.1") with dlopen("libvglfaker.so")
[VGL] WARNING: Could not load function "glXSwapIntervalEXT"
[VGL] WARNING: Could not load function "glXBindSwapBarrierNV"
[VGL] WARNING: Could not load function "glXJoinSwapGroupNV"
[VGL] WARNING: Could not load function "glXQueryFrameCountNV"
[VGL] WARNING: Could not load function "glXQueryMaxSwapGroupsNV"
[VGL] WARNING: Could not load function "glXQuerySwapGroupNV"
[VGL] WARNING: Could not load function "glXResetFrameCountNV"
Segmentation fault
danct12@debian:~$ 
```

**Comment by dcommander** [comment]
The first error is likely due to your GPU drivers not supporting Pbuffers.  See the "Sanity Check" section in the VirtualGL User's Guide for instructions on how to verify that.  We generally recommend an nVidia or AMD GPU with the vendor-supplied drivers.  Open source GPU drivers are going to be spotty in terms of performance and feature support and may not work with VirtualGL.  I'll check on the segfault.  It could be that /usr/bin/glxinfo, which is supplied by the operating system, is trying to load those function symbols using `glXGetProcAddress()`.  They might not be available in your GPU drivers (which would be consistent with Pbuffers not being available-- all of these are advanced GLX features that some open source drivers don't support), and glxinfo might not be properly guarding against a NULL return value from `glXGetProcAddress()`.  We supply our own version of glxinfo under /opt/VirtualGL/bin.

**Comment by dcommander** [comment]
Can you tell me which operating system you are running?

**Comment by Danct12** [comment]
Debian Stretch.

**Comment by dcommander** [comment]
OK, I tried Stretch but wasn't able to reproduce the failure.  What X11 driver are you using?

**Comment by Danct12** [comment]
VMware, forgot to give some more information, that I run VirtualGL remotely, from public to my home VM.

**Comment by dcommander** [comment]
I was finally able to reproduce a similar segfault in glxgears or glxspheres, but only if I force-uninstall the xserver-xorg-video-vmware package and reboot the VM.  If I do that, then a segfault occurs in the `glClear()` function, which VirtualGL calls within the body of `glXMakeCurrent()` (in order to clear a newly-created Pbuffer.)  When I re-install xserver-xorg-video-vmware and reboot, everything is fine.  I suspect that either something is wrong with your driver installation or your 3D X server isn't configured to use the VMWare driver.

**Comment by dcommander** [comment]
OK, I just re-read your comment and realized that you were giving me the client-side X11 driver.  I need to know:

* Server-side GPU, driver, and O/S?
* Client-side host O/S?

I already know that you're using a VMWare guest as a VirtualGL client, although I struggle to figure out why.  Most people use TurboVNC, which provides a client for Mac, Windows, or Linux.

Some other things to try:
* Please run the "Sanity Check" procedure described at the end of [this section](https://cdn.rawgit.com/VirtualGL/virtualgl/master/doc/index.html#hd006002) of the User's Guide on the server machine.  Whether or not that produces the same segfault will give some indication as to what might be wrong.  If this procedure still produces a segfault, then it's likely that the issue is related to the drivers on the server.
* Please try setting `VGL_PROBEGLX=0` in the environment on the server prior to executing vglrun.

**Comment by dcommander** [comment]
@Danct12 please provide the requested information.

**Comment by Danct12** [comment]
Apologize for no answer for a few days, I was busy with my life. Just tried it again today with the client's IP `DISPLAY=clientip` when before vglrun and that seemed to work.

Server-side (host):
- GPU: NVIDIA Geforce GTX 1050 Ti
- Driver: Proprietary
- Distro: Arch Linux

Client-side:
Android + XServer XSDL

**Comment by dcommander** [comment]
Now I'm very confused.  You said previously that you are using Debian Stretch and VMWare.  Where do those platforms fit into your configuration?  Please provide me with a complete picture.

**Comment by Danct12** [comment]
I thought you mean the VMs distro, Debian Stretch is the distro in the VM. I use Arch on my host.
![image](https://user-images.githubusercontent.com/19162768/44444492-4e185700-a607-11e8-8e65-1e5ba4655240.png)

**Comment by dcommander** [comment]
Ah, so effectively the VGL server is Stretch with the VMWare drivers, and the client is Android.  That makes more sense.  How are you connecting from client to server?  Did you build the VirtualGL Client for Android?  The fact that `DISPLAY=clientip` worked around the problem would suggest to me that SSH X11 tunneling isn't working properly from your Android client, or perhaps you didn't use the vglconnect script.  The segfault seems to be due to the VMWare drivers.  It seems that the X client side of the VMWare OpenGL stack is not tolerant of communicating with a different driver on the X server.  That's why I suggested `VGL_PROBEGLX=0`.  VirtualGL normally passes a few GLX commands to the 2D X server in order to probe for client-side stereo capabilities, but `VGL_PROBEGLX=0` disables that behavior.  It is specifically meant for cases like this in which the X-client-side OpenGL stack crashes when attempting to use remote GLX with a different X-server-side OpenGL stack.  The nVidia proprietary drivers used to have that same problem.

**Comment by dcommander** [comment]
Well, my answer remains the same.  Try setting `VGL_PROBEGLX=0` on the server to eliminate the segfault, and look closely at whether SSH X11 tunneling is being enabled from the client.  When you use vglconnect to connect to the server, the `DISPLAY` environment variable in the SSH session should have the form `localhost:n.0`, and the `SSH_CLIENT` environment variable should have the form `{client IP address} {port} {port}`.  vglrun attempts to detect whether SSH X11 forwarding is enabled, based on the values of `SSH_CLIENT` and `DISPLAY`, and set the `VGL_CLIENT` variable accordingly.  Somehow, that is not happening properly in your case.  I'm not sure how Linux Deploy interacts with XSDL, but that would be the first place I would look.  Your platform is very non-standard and is likely the source of the problems you are having.  In the future, please provide all of the relevant platform details in your bug report.
