### ISSUE TITLE
How VirtualGL sends data to X proxy?

### ISSUE THREAD

**Issue by liuty10** [VirtualGL/virtualgl#81]
FIGURE 5: In-Process GLX Forking with an X Proxy in the link below:
https://virtualgl.org/About/Background

When the application calls glxSwapBuffer(), the VirtualGL intercept this function. The VirtualGL reads back the Pbuffer and sends the data to X Proxy.  If my understanding is correct, how VirtualGL sends data to the X proxy? 
I find the callstack is: glxSwapBuffers()-> vm->readback()->SendX11()->SendFrame()->q.Spoil()->add?
I am still not clear about the whole callstack.

Does VirtualGL call XPutImage()? What kind of request the VirtualGL send to the X Poxy?
How about 2D applications? The 2D apps just interact with X Proxy directly?

**Comment by dcommander** [comment]
Yes, VGL calls `fbx_write()`, which calls `XShmPutImage()`, but that occurs in a different thread (the blitter thread.) The Spoil() stuff drops the frame unless the blitter thread is ready to draw it, but that behavior can be disabled with `VGL_SPOIL=0` or `vglrun -sp`.

**Comment by liuty10** [comment]
These information are really helpful, but I think I need more.
I have added some code in both TurboVNC server and client, but I am still not clear about the details.

Could you please draw some pictures to show how VNC and VirtualGL work in detail? Especially, how many threads are there and how they cooperate? and the key functions. 

I appreciate it if you can help. We can use Google doc and have an online meeting if you are also interested.

**Comment by dcommander** [comment]
If you want to pay me as a consultant, then I’m more than happy to provide custom training for you. Otherwise, I do not have time to provide free one-on-one instruction to every member of the VirtualGL community. My time is valuable and is best spent improving the product. Our documentation is better than that of most open source projects. It also includes many pictures. You can also probably find further information regarding the VirtualGL threading model by searching for “thread” on the current VirtualGL-users mailing list (Google Groups) or the old VirtualGL-users mailing list (SourceForge.) I have already given you more free information than most
open source developers would have given you. Most would have just told you to refer to the code. I do this for a living, so time is money for me. I have already donated a significant amount of my time/money toward furthering your understanding. I cannot afford to donate anymore.

**Comment by dcommander** [comment]
I consult on an hourly basis, but with corporations, not with students. I am not trying to take money from a student. I am just saying that I cannot afford to spend more than a token amount of time explaining the product unless that is in the context of a professional relationship. I had to learn how to do all of this myself. You can too.

**Comment by liuty10** [comment]
Thank you very much.

You mentioned that VGL calls fbx_write(), which calls XShmPutImage(), but that occurs in a different thread (the blitter thread.)

When VGL calls fbx_write()? I use gdb to debug the game step by step. I can enter glXSwapBuffer, but I can not make a break point and stop in fbx_write() function. Can you tell me why?

VGL intercept the glXSwapBuffer() function, and I would like to pass timestamps from glXSwapBuffer() to the XShmPutImage(). However, it seems that these two functions works in two separate process, am I right?
