### ISSUE TITLE
How are GPU resources distributed between multiple users?

### ISSUE THREAD

**Issue by scganterh** [VirtualGL/virtualgl#97]
Hi,

I am measuring the performance of an OpenGL application that is executed by multiple users at the same time. All users use the `vglrun` command to be able to use the shared GPU installed on an application server.

I wonder how the GPU resources are distributed between these users. Is this logic implemented in VirtualGL? Or maybe it is implemented by the GPU's driver? Does it matter that the instances of the application are run by different users? Is this the same as a single user running multiple instances of the application?

Maybe this information is available somewhere and I haven't found it yet. Anyway, I would appreciate if someone could point me in the right direction.

Thanks.

**Comment by dcommander** [comment]
They aren't.  VirtualGL uses whichever GPU is attached to the 3D X server specified in `VGL_DISPLAY`, so in order to load balance, you have to:

1. Configure the system such that each GPU is attached to a separate 3D X server screen (e.g. :0.0, :0.1, :0.2 etc.) or a separate 3D X server instance (e.g. :0.0, :1.0, :2.0, etc.)
2. Wrap VirtualGL with a portal or some other solution that sets `VGL_DISPLAY` automatically based on the GPU load.

There is an outstanding feature request in need of funding (#89) that would implement rudimentary load balancing logic in vglrun (basically, if `VGL_DISPLAY=auto`, vglrun would set `VGL_DISPLAY` to point to the least-loaded GPU.)

**Comment by dcommander** [comment]
Re-reading your question, you may have been asking how GPU resources are *shared* (as opposed to distributed) if all users are using the same GPU.  In that case, yes, it is handled by the driver.  How many simultaneous users can effectively share the GPU depends on how demanding the application is of GPU resources, so it varies from application to application.  I know that some VirtualGL shops provision 40-50 users per GPU, but they aren't necessarily simultaneous users.

**Comment by dcommander** [comment]
And no, it doesn't matter which account the application instances are running under.  From OpenGL's point of view, they're all just processes and threads.
